name: tau_nn
dependencies:
  - python=3.8
  - tensorflow
  - keras
  - scikit-learn
  - matplotlib
  - pip
  - ipykernel
  - pip:
    - numpy
    - h5py
    - scipy==1.5.4
    - mplhep
    - jupyter
    - uproot4==4.0.0
    - awkward==1.2.0
    - hist[plot]
    - coffea==0.7.1
