name: tau_training
dependencies:
  - python=3.8
  - tensorflow
  - keras
  - scikit-learn
  - matplotlib
  - numpy
  - pip
  - ipykernel
  - pip:
    - h5py==2.10.0
    - scipy==1.5.4
    - mplhep
    - jupyter