// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config13_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;
output  [8:0] ap_return_7;
output  [8:0] ap_return_8;
output  [8:0] ap_return_9;
output  [8:0] ap_return_10;
output  [8:0] ap_return_11;
output  [8:0] ap_return_12;
output  [8:0] ap_return_13;

wire   [0:0] p_Result_s_fu_224_p3;
wire   [0:0] p_Result_316_fu_204_p1;
wire   [0:0] and_ln420_fu_240_p2;
wire   [8:0] p_Val2_s_fu_214_p4;
wire   [8:0] zext_ln423_fu_246_p1;
wire   [5:0] tmp25_fu_256_p4;
wire   [8:0] p_Val2_112_fu_250_p2;
wire   [0:0] tmp_fu_278_p3;
wire   [0:0] Range1_all_zeros_fu_272_p2;
wire   [0:0] Range1_all_ones_fu_266_p2;
wire   [0:0] p_Result_317_fu_232_p3;
wire   [0:0] select_ln934_fu_286_p3;
wire   [0:0] deleted_zeros_fu_294_p3;
wire   [0:0] icmp_ln1695_fu_208_p2;
wire   [8:0] select_ln348_fu_302_p3;
wire   [0:0] p_Result_279_fu_334_p3;
wire   [0:0] p_Result_318_fu_200_p1;
wire   [0:0] and_ln420_55_fu_350_p2;
wire   [8:0] p_Val2_113_fu_324_p4;
wire   [8:0] zext_ln423_55_fu_356_p1;
wire   [5:0] tmp_30_fu_366_p4;
wire   [8:0] p_Val2_114_fu_360_p2;
wire   [0:0] tmp_173_fu_388_p3;
wire   [0:0] Range1_all_zeros_55_fu_382_p2;
wire   [0:0] Range1_all_ones_55_fu_376_p2;
wire   [0:0] p_Result_319_fu_342_p3;
wire   [0:0] select_ln934_55_fu_396_p3;
wire   [0:0] deleted_zeros_55_fu_404_p3;
wire   [0:0] icmp_ln1695_55_fu_318_p2;
wire   [8:0] select_ln348_55_fu_412_p3;
wire   [0:0] p_Result_282_fu_444_p3;
wire   [0:0] p_Result_320_fu_196_p1;
wire   [0:0] and_ln420_56_fu_460_p2;
wire   [8:0] p_Val2_115_fu_434_p4;
wire   [8:0] zext_ln423_56_fu_466_p1;
wire   [5:0] tmp_s_fu_476_p4;
wire   [8:0] p_Val2_116_fu_470_p2;
wire   [0:0] tmp_176_fu_498_p3;
wire   [0:0] Range1_all_zeros_56_fu_492_p2;
wire   [0:0] Range1_all_ones_56_fu_486_p2;
wire   [0:0] p_Result_321_fu_452_p3;
wire   [0:0] select_ln934_56_fu_506_p3;
wire   [0:0] deleted_zeros_56_fu_514_p3;
wire   [0:0] icmp_ln1695_56_fu_428_p2;
wire   [8:0] select_ln348_56_fu_522_p3;
wire   [0:0] p_Result_285_fu_554_p3;
wire   [0:0] p_Result_322_fu_192_p1;
wire   [0:0] and_ln420_57_fu_570_p2;
wire   [8:0] p_Val2_117_fu_544_p4;
wire   [8:0] zext_ln423_57_fu_576_p1;
wire   [5:0] tmp_62_fu_586_p4;
wire   [8:0] p_Val2_118_fu_580_p2;
wire   [0:0] tmp_179_fu_608_p3;
wire   [0:0] Range1_all_zeros_57_fu_602_p2;
wire   [0:0] Range1_all_ones_57_fu_596_p2;
wire   [0:0] p_Result_323_fu_562_p3;
wire   [0:0] select_ln934_57_fu_616_p3;
wire   [0:0] deleted_zeros_57_fu_624_p3;
wire   [0:0] icmp_ln1695_57_fu_538_p2;
wire   [8:0] select_ln348_57_fu_632_p3;
wire   [0:0] p_Result_288_fu_664_p3;
wire   [0:0] p_Result_324_fu_188_p1;
wire   [0:0] and_ln420_58_fu_680_p2;
wire   [8:0] p_Val2_119_fu_654_p4;
wire   [8:0] zext_ln423_58_fu_686_p1;
wire   [5:0] tmp_63_fu_696_p4;
wire   [8:0] p_Val2_120_fu_690_p2;
wire   [0:0] tmp_182_fu_718_p3;
wire   [0:0] Range1_all_zeros_58_fu_712_p2;
wire   [0:0] Range1_all_ones_58_fu_706_p2;
wire   [0:0] p_Result_325_fu_672_p3;
wire   [0:0] select_ln934_58_fu_726_p3;
wire   [0:0] deleted_zeros_58_fu_734_p3;
wire   [0:0] icmp_ln1695_58_fu_648_p2;
wire   [8:0] select_ln348_58_fu_742_p3;
wire   [0:0] p_Result_291_fu_774_p3;
wire   [0:0] p_Result_326_fu_184_p1;
wire   [0:0] and_ln420_59_fu_790_p2;
wire   [8:0] p_Val2_121_fu_764_p4;
wire   [8:0] zext_ln423_59_fu_796_p1;
wire   [5:0] tmp_64_fu_806_p4;
wire   [8:0] p_Val2_122_fu_800_p2;
wire   [0:0] tmp_185_fu_828_p3;
wire   [0:0] Range1_all_zeros_59_fu_822_p2;
wire   [0:0] Range1_all_ones_59_fu_816_p2;
wire   [0:0] p_Result_327_fu_782_p3;
wire   [0:0] select_ln934_59_fu_836_p3;
wire   [0:0] deleted_zeros_59_fu_844_p3;
wire   [0:0] icmp_ln1695_59_fu_758_p2;
wire   [8:0] select_ln348_59_fu_852_p3;
wire   [0:0] p_Result_294_fu_884_p3;
wire   [0:0] p_Result_328_fu_180_p1;
wire   [0:0] and_ln420_60_fu_900_p2;
wire   [8:0] p_Val2_123_fu_874_p4;
wire   [8:0] zext_ln423_60_fu_906_p1;
wire   [5:0] tmp_65_fu_916_p4;
wire   [8:0] p_Val2_124_fu_910_p2;
wire   [0:0] tmp_188_fu_938_p3;
wire   [0:0] Range1_all_zeros_60_fu_932_p2;
wire   [0:0] Range1_all_ones_60_fu_926_p2;
wire   [0:0] p_Result_329_fu_892_p3;
wire   [0:0] select_ln934_60_fu_946_p3;
wire   [0:0] deleted_zeros_60_fu_954_p3;
wire   [0:0] icmp_ln1695_60_fu_868_p2;
wire   [8:0] select_ln348_60_fu_962_p3;
wire   [0:0] p_Result_297_fu_994_p3;
wire   [0:0] p_Result_330_fu_176_p1;
wire   [0:0] and_ln420_61_fu_1010_p2;
wire   [8:0] p_Val2_125_fu_984_p4;
wire   [8:0] zext_ln423_61_fu_1016_p1;
wire   [5:0] tmp_66_fu_1026_p4;
wire   [8:0] p_Val2_126_fu_1020_p2;
wire   [0:0] tmp_191_fu_1048_p3;
wire   [0:0] Range1_all_zeros_61_fu_1042_p2;
wire   [0:0] Range1_all_ones_61_fu_1036_p2;
wire   [0:0] p_Result_331_fu_1002_p3;
wire   [0:0] select_ln934_61_fu_1056_p3;
wire   [0:0] deleted_zeros_61_fu_1064_p3;
wire   [0:0] icmp_ln1695_61_fu_978_p2;
wire   [8:0] select_ln348_61_fu_1072_p3;
wire   [0:0] p_Result_300_fu_1104_p3;
wire   [0:0] p_Result_332_fu_172_p1;
wire   [0:0] and_ln420_62_fu_1120_p2;
wire   [8:0] p_Val2_127_fu_1094_p4;
wire   [8:0] zext_ln423_62_fu_1126_p1;
wire   [5:0] tmp_67_fu_1136_p4;
wire   [8:0] p_Val2_128_fu_1130_p2;
wire   [0:0] tmp_194_fu_1158_p3;
wire   [0:0] Range1_all_zeros_62_fu_1152_p2;
wire   [0:0] Range1_all_ones_62_fu_1146_p2;
wire   [0:0] p_Result_333_fu_1112_p3;
wire   [0:0] select_ln934_62_fu_1166_p3;
wire   [0:0] deleted_zeros_62_fu_1174_p3;
wire   [0:0] icmp_ln1695_62_fu_1088_p2;
wire   [8:0] select_ln348_62_fu_1182_p3;
wire   [0:0] p_Result_303_fu_1214_p3;
wire   [0:0] p_Result_334_fu_168_p1;
wire   [0:0] and_ln420_63_fu_1230_p2;
wire   [8:0] p_Val2_129_fu_1204_p4;
wire   [8:0] zext_ln423_63_fu_1236_p1;
wire   [5:0] tmp_68_fu_1246_p4;
wire   [8:0] p_Val2_130_fu_1240_p2;
wire   [0:0] tmp_197_fu_1268_p3;
wire   [0:0] Range1_all_zeros_63_fu_1262_p2;
wire   [0:0] Range1_all_ones_63_fu_1256_p2;
wire   [0:0] p_Result_335_fu_1222_p3;
wire   [0:0] select_ln934_63_fu_1276_p3;
wire   [0:0] deleted_zeros_63_fu_1284_p3;
wire   [0:0] icmp_ln1695_63_fu_1198_p2;
wire   [8:0] select_ln348_63_fu_1292_p3;
wire   [0:0] p_Result_306_fu_1324_p3;
wire   [0:0] p_Result_336_fu_164_p1;
wire   [0:0] and_ln420_64_fu_1340_p2;
wire   [8:0] p_Val2_131_fu_1314_p4;
wire   [8:0] zext_ln423_64_fu_1346_p1;
wire   [5:0] tmp_69_fu_1356_p4;
wire   [8:0] p_Val2_132_fu_1350_p2;
wire   [0:0] tmp_200_fu_1378_p3;
wire   [0:0] Range1_all_zeros_64_fu_1372_p2;
wire   [0:0] Range1_all_ones_64_fu_1366_p2;
wire   [0:0] p_Result_337_fu_1332_p3;
wire   [0:0] select_ln934_64_fu_1386_p3;
wire   [0:0] deleted_zeros_64_fu_1394_p3;
wire   [0:0] icmp_ln1695_64_fu_1308_p2;
wire   [8:0] select_ln348_64_fu_1402_p3;
wire   [0:0] p_Result_309_fu_1434_p3;
wire   [0:0] p_Result_338_fu_160_p1;
wire   [0:0] and_ln420_65_fu_1450_p2;
wire   [8:0] p_Val2_133_fu_1424_p4;
wire   [8:0] zext_ln423_65_fu_1456_p1;
wire   [5:0] tmp_70_fu_1466_p4;
wire   [8:0] p_Val2_134_fu_1460_p2;
wire   [0:0] tmp_203_fu_1488_p3;
wire   [0:0] Range1_all_zeros_65_fu_1482_p2;
wire   [0:0] Range1_all_ones_65_fu_1476_p2;
wire   [0:0] p_Result_339_fu_1442_p3;
wire   [0:0] select_ln934_65_fu_1496_p3;
wire   [0:0] deleted_zeros_65_fu_1504_p3;
wire   [0:0] icmp_ln1695_65_fu_1418_p2;
wire   [8:0] select_ln348_65_fu_1512_p3;
wire   [0:0] p_Result_312_fu_1544_p3;
wire   [0:0] p_Result_340_fu_156_p1;
wire   [0:0] and_ln420_66_fu_1560_p2;
wire   [8:0] p_Val2_135_fu_1534_p4;
wire   [8:0] zext_ln423_66_fu_1566_p1;
wire   [5:0] tmp_71_fu_1576_p4;
wire   [8:0] p_Val2_136_fu_1570_p2;
wire   [0:0] tmp_206_fu_1598_p3;
wire   [0:0] Range1_all_zeros_66_fu_1592_p2;
wire   [0:0] Range1_all_ones_66_fu_1586_p2;
wire   [0:0] p_Result_341_fu_1552_p3;
wire   [0:0] select_ln934_66_fu_1606_p3;
wire   [0:0] deleted_zeros_66_fu_1614_p3;
wire   [0:0] icmp_ln1695_66_fu_1528_p2;
wire   [8:0] select_ln348_66_fu_1622_p3;
wire   [0:0] p_Result_315_fu_1654_p3;
wire   [0:0] p_Result_342_fu_152_p1;
wire   [0:0] and_ln420_67_fu_1670_p2;
wire   [8:0] p_Val2_137_fu_1644_p4;
wire   [8:0] zext_ln423_67_fu_1676_p1;
wire   [5:0] tmp_72_fu_1686_p4;
wire   [8:0] p_Val2_138_fu_1680_p2;
wire   [0:0] tmp_209_fu_1708_p3;
wire   [0:0] Range1_all_zeros_67_fu_1702_p2;
wire   [0:0] Range1_all_ones_67_fu_1696_p2;
wire   [0:0] p_Result_343_fu_1662_p3;
wire   [0:0] select_ln934_67_fu_1716_p3;
wire   [0:0] deleted_zeros_67_fu_1724_p3;
wire   [0:0] icmp_ln1695_67_fu_1638_p2;
wire   [8:0] select_ln348_67_fu_1732_p3;
wire   [8:0] select_ln1695_fu_310_p3;
wire   [8:0] select_ln1695_55_fu_420_p3;
wire   [8:0] select_ln1695_56_fu_530_p3;
wire   [8:0] select_ln1695_57_fu_640_p3;
wire   [8:0] select_ln1695_58_fu_750_p3;
wire   [8:0] select_ln1695_59_fu_860_p3;
wire   [8:0] select_ln1695_60_fu_970_p3;
wire   [8:0] select_ln1695_61_fu_1080_p3;
wire   [8:0] select_ln1695_62_fu_1190_p3;
wire   [8:0] select_ln1695_63_fu_1300_p3;
wire   [8:0] select_ln1695_64_fu_1410_p3;
wire   [8:0] select_ln1695_65_fu_1520_p3;
wire   [8:0] select_ln1695_66_fu_1630_p3;
wire   [8:0] select_ln1695_67_fu_1740_p3;
wire    ap_ce_reg;

assign Range1_all_ones_55_fu_376_p2 = ((tmp_30_fu_366_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_56_fu_486_p2 = ((tmp_s_fu_476_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_57_fu_596_p2 = ((tmp_62_fu_586_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_58_fu_706_p2 = ((tmp_63_fu_696_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_59_fu_816_p2 = ((tmp_64_fu_806_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_60_fu_926_p2 = ((tmp_65_fu_916_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_61_fu_1036_p2 = ((tmp_66_fu_1026_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_62_fu_1146_p2 = ((tmp_67_fu_1136_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_63_fu_1256_p2 = ((tmp_68_fu_1246_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_64_fu_1366_p2 = ((tmp_69_fu_1356_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_65_fu_1476_p2 = ((tmp_70_fu_1466_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_66_fu_1586_p2 = ((tmp_71_fu_1576_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_67_fu_1696_p2 = ((tmp_72_fu_1686_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_266_p2 = ((tmp25_fu_256_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_55_fu_382_p2 = ((tmp_30_fu_366_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_56_fu_492_p2 = ((tmp_s_fu_476_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_57_fu_602_p2 = ((tmp_62_fu_586_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_58_fu_712_p2 = ((tmp_63_fu_696_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_59_fu_822_p2 = ((tmp_64_fu_806_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_60_fu_932_p2 = ((tmp_65_fu_916_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_61_fu_1042_p2 = ((tmp_66_fu_1026_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_62_fu_1152_p2 = ((tmp_67_fu_1136_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_63_fu_1262_p2 = ((tmp_68_fu_1246_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_64_fu_1372_p2 = ((tmp_69_fu_1356_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_65_fu_1482_p2 = ((tmp_70_fu_1466_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_66_fu_1592_p2 = ((tmp_71_fu_1576_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_67_fu_1702_p2 = ((tmp_72_fu_1686_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_272_p2 = ((tmp25_fu_256_p4 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln420_55_fu_350_p2 = (p_Result_318_fu_200_p1 & p_Result_279_fu_334_p3);

assign and_ln420_56_fu_460_p2 = (p_Result_320_fu_196_p1 & p_Result_282_fu_444_p3);

assign and_ln420_57_fu_570_p2 = (p_Result_322_fu_192_p1 & p_Result_285_fu_554_p3);

assign and_ln420_58_fu_680_p2 = (p_Result_324_fu_188_p1 & p_Result_288_fu_664_p3);

assign and_ln420_59_fu_790_p2 = (p_Result_326_fu_184_p1 & p_Result_291_fu_774_p3);

assign and_ln420_60_fu_900_p2 = (p_Result_328_fu_180_p1 & p_Result_294_fu_884_p3);

assign and_ln420_61_fu_1010_p2 = (p_Result_330_fu_176_p1 & p_Result_297_fu_994_p3);

assign and_ln420_62_fu_1120_p2 = (p_Result_332_fu_172_p1 & p_Result_300_fu_1104_p3);

assign and_ln420_63_fu_1230_p2 = (p_Result_334_fu_168_p1 & p_Result_303_fu_1214_p3);

assign and_ln420_64_fu_1340_p2 = (p_Result_336_fu_164_p1 & p_Result_306_fu_1324_p3);

assign and_ln420_65_fu_1450_p2 = (p_Result_338_fu_160_p1 & p_Result_309_fu_1434_p3);

assign and_ln420_66_fu_1560_p2 = (p_Result_340_fu_156_p1 & p_Result_312_fu_1544_p3);

assign and_ln420_67_fu_1670_p2 = (p_Result_342_fu_152_p1 & p_Result_315_fu_1654_p3);

assign and_ln420_fu_240_p2 = (p_Result_s_fu_224_p3 & p_Result_316_fu_204_p1);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1695_fu_310_p3;

assign ap_return_1 = select_ln1695_55_fu_420_p3;

assign ap_return_10 = select_ln1695_64_fu_1410_p3;

assign ap_return_11 = select_ln1695_65_fu_1520_p3;

assign ap_return_12 = select_ln1695_66_fu_1630_p3;

assign ap_return_13 = select_ln1695_67_fu_1740_p3;

assign ap_return_2 = select_ln1695_56_fu_530_p3;

assign ap_return_3 = select_ln1695_57_fu_640_p3;

assign ap_return_4 = select_ln1695_58_fu_750_p3;

assign ap_return_5 = select_ln1695_59_fu_860_p3;

assign ap_return_6 = select_ln1695_60_fu_970_p3;

assign ap_return_7 = select_ln1695_61_fu_1080_p3;

assign ap_return_8 = select_ln1695_62_fu_1190_p3;

assign ap_return_9 = select_ln1695_63_fu_1300_p3;

assign deleted_zeros_55_fu_404_p3 = ((p_Result_319_fu_342_p3[0:0] == 1'b1) ? select_ln934_55_fu_396_p3 : Range1_all_zeros_55_fu_382_p2);

assign deleted_zeros_56_fu_514_p3 = ((p_Result_321_fu_452_p3[0:0] == 1'b1) ? select_ln934_56_fu_506_p3 : Range1_all_zeros_56_fu_492_p2);

assign deleted_zeros_57_fu_624_p3 = ((p_Result_323_fu_562_p3[0:0] == 1'b1) ? select_ln934_57_fu_616_p3 : Range1_all_zeros_57_fu_602_p2);

assign deleted_zeros_58_fu_734_p3 = ((p_Result_325_fu_672_p3[0:0] == 1'b1) ? select_ln934_58_fu_726_p3 : Range1_all_zeros_58_fu_712_p2);

assign deleted_zeros_59_fu_844_p3 = ((p_Result_327_fu_782_p3[0:0] == 1'b1) ? select_ln934_59_fu_836_p3 : Range1_all_zeros_59_fu_822_p2);

assign deleted_zeros_60_fu_954_p3 = ((p_Result_329_fu_892_p3[0:0] == 1'b1) ? select_ln934_60_fu_946_p3 : Range1_all_zeros_60_fu_932_p2);

assign deleted_zeros_61_fu_1064_p3 = ((p_Result_331_fu_1002_p3[0:0] == 1'b1) ? select_ln934_61_fu_1056_p3 : Range1_all_zeros_61_fu_1042_p2);

assign deleted_zeros_62_fu_1174_p3 = ((p_Result_333_fu_1112_p3[0:0] == 1'b1) ? select_ln934_62_fu_1166_p3 : Range1_all_zeros_62_fu_1152_p2);

assign deleted_zeros_63_fu_1284_p3 = ((p_Result_335_fu_1222_p3[0:0] == 1'b1) ? select_ln934_63_fu_1276_p3 : Range1_all_zeros_63_fu_1262_p2);

assign deleted_zeros_64_fu_1394_p3 = ((p_Result_337_fu_1332_p3[0:0] == 1'b1) ? select_ln934_64_fu_1386_p3 : Range1_all_zeros_64_fu_1372_p2);

assign deleted_zeros_65_fu_1504_p3 = ((p_Result_339_fu_1442_p3[0:0] == 1'b1) ? select_ln934_65_fu_1496_p3 : Range1_all_zeros_65_fu_1482_p2);

assign deleted_zeros_66_fu_1614_p3 = ((p_Result_341_fu_1552_p3[0:0] == 1'b1) ? select_ln934_66_fu_1606_p3 : Range1_all_zeros_66_fu_1592_p2);

assign deleted_zeros_67_fu_1724_p3 = ((p_Result_343_fu_1662_p3[0:0] == 1'b1) ? select_ln934_67_fu_1716_p3 : Range1_all_zeros_67_fu_1702_p2);

assign deleted_zeros_fu_294_p3 = ((p_Result_317_fu_232_p3[0:0] == 1'b1) ? select_ln934_fu_286_p3 : Range1_all_zeros_fu_272_p2);

assign icmp_ln1695_55_fu_318_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_56_fu_428_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_57_fu_538_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_58_fu_648_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_59_fu_758_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_60_fu_868_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_61_fu_978_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_62_fu_1088_p2 = (($signed(p_read8) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_63_fu_1198_p2 = (($signed(p_read9) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_64_fu_1308_p2 = (($signed(p_read11) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_65_fu_1418_p2 = (($signed(p_read12) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_66_fu_1528_p2 = (($signed(p_read13) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_67_fu_1638_p2 = (($signed(p_read14) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_fu_208_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign p_Result_279_fu_334_p3 = p_read1[32'd1];

assign p_Result_282_fu_444_p3 = p_read2[32'd1];

assign p_Result_285_fu_554_p3 = p_read3[32'd1];

assign p_Result_288_fu_664_p3 = p_read4[32'd1];

assign p_Result_291_fu_774_p3 = p_read5[32'd1];

assign p_Result_294_fu_884_p3 = p_read6[32'd1];

assign p_Result_297_fu_994_p3 = p_read7[32'd1];

assign p_Result_300_fu_1104_p3 = p_read8[32'd1];

assign p_Result_303_fu_1214_p3 = p_read9[32'd1];

assign p_Result_306_fu_1324_p3 = p_read11[32'd1];

assign p_Result_309_fu_1434_p3 = p_read12[32'd1];

assign p_Result_312_fu_1544_p3 = p_read13[32'd1];

assign p_Result_315_fu_1654_p3 = p_read14[32'd1];

assign p_Result_316_fu_204_p1 = p_read[0:0];

assign p_Result_317_fu_232_p3 = p_read[32'd9];

assign p_Result_318_fu_200_p1 = p_read1[0:0];

assign p_Result_319_fu_342_p3 = p_read1[32'd9];

assign p_Result_320_fu_196_p1 = p_read2[0:0];

assign p_Result_321_fu_452_p3 = p_read2[32'd9];

assign p_Result_322_fu_192_p1 = p_read3[0:0];

assign p_Result_323_fu_562_p3 = p_read3[32'd9];

assign p_Result_324_fu_188_p1 = p_read4[0:0];

assign p_Result_325_fu_672_p3 = p_read4[32'd9];

assign p_Result_326_fu_184_p1 = p_read5[0:0];

assign p_Result_327_fu_782_p3 = p_read5[32'd9];

assign p_Result_328_fu_180_p1 = p_read6[0:0];

assign p_Result_329_fu_892_p3 = p_read6[32'd9];

assign p_Result_330_fu_176_p1 = p_read7[0:0];

assign p_Result_331_fu_1002_p3 = p_read7[32'd9];

assign p_Result_332_fu_172_p1 = p_read8[0:0];

assign p_Result_333_fu_1112_p3 = p_read8[32'd9];

assign p_Result_334_fu_168_p1 = p_read9[0:0];

assign p_Result_335_fu_1222_p3 = p_read9[32'd9];

assign p_Result_336_fu_164_p1 = p_read11[0:0];

assign p_Result_337_fu_1332_p3 = p_read11[32'd9];

assign p_Result_338_fu_160_p1 = p_read12[0:0];

assign p_Result_339_fu_1442_p3 = p_read12[32'd9];

assign p_Result_340_fu_156_p1 = p_read13[0:0];

assign p_Result_341_fu_1552_p3 = p_read13[32'd9];

assign p_Result_342_fu_152_p1 = p_read14[0:0];

assign p_Result_343_fu_1662_p3 = p_read14[32'd9];

assign p_Result_s_fu_224_p3 = p_read[32'd1];

assign p_Val2_112_fu_250_p2 = (p_Val2_s_fu_214_p4 + zext_ln423_fu_246_p1);

assign p_Val2_113_fu_324_p4 = {{p_read1[9:1]}};

assign p_Val2_114_fu_360_p2 = (p_Val2_113_fu_324_p4 + zext_ln423_55_fu_356_p1);

assign p_Val2_115_fu_434_p4 = {{p_read2[9:1]}};

assign p_Val2_116_fu_470_p2 = (p_Val2_115_fu_434_p4 + zext_ln423_56_fu_466_p1);

assign p_Val2_117_fu_544_p4 = {{p_read3[9:1]}};

assign p_Val2_118_fu_580_p2 = (p_Val2_117_fu_544_p4 + zext_ln423_57_fu_576_p1);

assign p_Val2_119_fu_654_p4 = {{p_read4[9:1]}};

assign p_Val2_120_fu_690_p2 = (p_Val2_119_fu_654_p4 + zext_ln423_58_fu_686_p1);

assign p_Val2_121_fu_764_p4 = {{p_read5[9:1]}};

assign p_Val2_122_fu_800_p2 = (p_Val2_121_fu_764_p4 + zext_ln423_59_fu_796_p1);

assign p_Val2_123_fu_874_p4 = {{p_read6[9:1]}};

assign p_Val2_124_fu_910_p2 = (p_Val2_123_fu_874_p4 + zext_ln423_60_fu_906_p1);

assign p_Val2_125_fu_984_p4 = {{p_read7[9:1]}};

assign p_Val2_126_fu_1020_p2 = (p_Val2_125_fu_984_p4 + zext_ln423_61_fu_1016_p1);

assign p_Val2_127_fu_1094_p4 = {{p_read8[9:1]}};

assign p_Val2_128_fu_1130_p2 = (p_Val2_127_fu_1094_p4 + zext_ln423_62_fu_1126_p1);

assign p_Val2_129_fu_1204_p4 = {{p_read9[9:1]}};

assign p_Val2_130_fu_1240_p2 = (p_Val2_129_fu_1204_p4 + zext_ln423_63_fu_1236_p1);

assign p_Val2_131_fu_1314_p4 = {{p_read11[9:1]}};

assign p_Val2_132_fu_1350_p2 = (p_Val2_131_fu_1314_p4 + zext_ln423_64_fu_1346_p1);

assign p_Val2_133_fu_1424_p4 = {{p_read12[9:1]}};

assign p_Val2_134_fu_1460_p2 = (p_Val2_133_fu_1424_p4 + zext_ln423_65_fu_1456_p1);

assign p_Val2_135_fu_1534_p4 = {{p_read13[9:1]}};

assign p_Val2_136_fu_1570_p2 = (p_Val2_135_fu_1534_p4 + zext_ln423_66_fu_1566_p1);

assign p_Val2_137_fu_1644_p4 = {{p_read14[9:1]}};

assign p_Val2_138_fu_1680_p2 = (p_Val2_137_fu_1644_p4 + zext_ln423_67_fu_1676_p1);

assign p_Val2_s_fu_214_p4 = {{p_read[9:1]}};

assign select_ln1695_55_fu_420_p3 = ((icmp_ln1695_55_fu_318_p2[0:0] == 1'b1) ? select_ln348_55_fu_412_p3 : 9'd0);

assign select_ln1695_56_fu_530_p3 = ((icmp_ln1695_56_fu_428_p2[0:0] == 1'b1) ? select_ln348_56_fu_522_p3 : 9'd0);

assign select_ln1695_57_fu_640_p3 = ((icmp_ln1695_57_fu_538_p2[0:0] == 1'b1) ? select_ln348_57_fu_632_p3 : 9'd0);

assign select_ln1695_58_fu_750_p3 = ((icmp_ln1695_58_fu_648_p2[0:0] == 1'b1) ? select_ln348_58_fu_742_p3 : 9'd0);

assign select_ln1695_59_fu_860_p3 = ((icmp_ln1695_59_fu_758_p2[0:0] == 1'b1) ? select_ln348_59_fu_852_p3 : 9'd0);

assign select_ln1695_60_fu_970_p3 = ((icmp_ln1695_60_fu_868_p2[0:0] == 1'b1) ? select_ln348_60_fu_962_p3 : 9'd0);

assign select_ln1695_61_fu_1080_p3 = ((icmp_ln1695_61_fu_978_p2[0:0] == 1'b1) ? select_ln348_61_fu_1072_p3 : 9'd0);

assign select_ln1695_62_fu_1190_p3 = ((icmp_ln1695_62_fu_1088_p2[0:0] == 1'b1) ? select_ln348_62_fu_1182_p3 : 9'd0);

assign select_ln1695_63_fu_1300_p3 = ((icmp_ln1695_63_fu_1198_p2[0:0] == 1'b1) ? select_ln348_63_fu_1292_p3 : 9'd0);

assign select_ln1695_64_fu_1410_p3 = ((icmp_ln1695_64_fu_1308_p2[0:0] == 1'b1) ? select_ln348_64_fu_1402_p3 : 9'd0);

assign select_ln1695_65_fu_1520_p3 = ((icmp_ln1695_65_fu_1418_p2[0:0] == 1'b1) ? select_ln348_65_fu_1512_p3 : 9'd0);

assign select_ln1695_66_fu_1630_p3 = ((icmp_ln1695_66_fu_1528_p2[0:0] == 1'b1) ? select_ln348_66_fu_1622_p3 : 9'd0);

assign select_ln1695_67_fu_1740_p3 = ((icmp_ln1695_67_fu_1638_p2[0:0] == 1'b1) ? select_ln348_67_fu_1732_p3 : 9'd0);

assign select_ln1695_fu_310_p3 = ((icmp_ln1695_fu_208_p2[0:0] == 1'b1) ? select_ln348_fu_302_p3 : 9'd0);

assign select_ln348_55_fu_412_p3 = ((deleted_zeros_55_fu_404_p3[0:0] == 1'b1) ? p_Val2_114_fu_360_p2 : 9'd511);

assign select_ln348_56_fu_522_p3 = ((deleted_zeros_56_fu_514_p3[0:0] == 1'b1) ? p_Val2_116_fu_470_p2 : 9'd511);

assign select_ln348_57_fu_632_p3 = ((deleted_zeros_57_fu_624_p3[0:0] == 1'b1) ? p_Val2_118_fu_580_p2 : 9'd511);

assign select_ln348_58_fu_742_p3 = ((deleted_zeros_58_fu_734_p3[0:0] == 1'b1) ? p_Val2_120_fu_690_p2 : 9'd511);

assign select_ln348_59_fu_852_p3 = ((deleted_zeros_59_fu_844_p3[0:0] == 1'b1) ? p_Val2_122_fu_800_p2 : 9'd511);

assign select_ln348_60_fu_962_p3 = ((deleted_zeros_60_fu_954_p3[0:0] == 1'b1) ? p_Val2_124_fu_910_p2 : 9'd511);

assign select_ln348_61_fu_1072_p3 = ((deleted_zeros_61_fu_1064_p3[0:0] == 1'b1) ? p_Val2_126_fu_1020_p2 : 9'd511);

assign select_ln348_62_fu_1182_p3 = ((deleted_zeros_62_fu_1174_p3[0:0] == 1'b1) ? p_Val2_128_fu_1130_p2 : 9'd511);

assign select_ln348_63_fu_1292_p3 = ((deleted_zeros_63_fu_1284_p3[0:0] == 1'b1) ? p_Val2_130_fu_1240_p2 : 9'd511);

assign select_ln348_64_fu_1402_p3 = ((deleted_zeros_64_fu_1394_p3[0:0] == 1'b1) ? p_Val2_132_fu_1350_p2 : 9'd511);

assign select_ln348_65_fu_1512_p3 = ((deleted_zeros_65_fu_1504_p3[0:0] == 1'b1) ? p_Val2_134_fu_1460_p2 : 9'd511);

assign select_ln348_66_fu_1622_p3 = ((deleted_zeros_66_fu_1614_p3[0:0] == 1'b1) ? p_Val2_136_fu_1570_p2 : 9'd511);

assign select_ln348_67_fu_1732_p3 = ((deleted_zeros_67_fu_1724_p3[0:0] == 1'b1) ? p_Val2_138_fu_1680_p2 : 9'd511);

assign select_ln348_fu_302_p3 = ((deleted_zeros_fu_294_p3[0:0] == 1'b1) ? p_Val2_112_fu_250_p2 : 9'd511);

assign select_ln934_55_fu_396_p3 = ((tmp_173_fu_388_p3[0:0] == 1'b1) ? Range1_all_zeros_55_fu_382_p2 : Range1_all_ones_55_fu_376_p2);

assign select_ln934_56_fu_506_p3 = ((tmp_176_fu_498_p3[0:0] == 1'b1) ? Range1_all_zeros_56_fu_492_p2 : Range1_all_ones_56_fu_486_p2);

assign select_ln934_57_fu_616_p3 = ((tmp_179_fu_608_p3[0:0] == 1'b1) ? Range1_all_zeros_57_fu_602_p2 : Range1_all_ones_57_fu_596_p2);

assign select_ln934_58_fu_726_p3 = ((tmp_182_fu_718_p3[0:0] == 1'b1) ? Range1_all_zeros_58_fu_712_p2 : Range1_all_ones_58_fu_706_p2);

assign select_ln934_59_fu_836_p3 = ((tmp_185_fu_828_p3[0:0] == 1'b1) ? Range1_all_zeros_59_fu_822_p2 : Range1_all_ones_59_fu_816_p2);

assign select_ln934_60_fu_946_p3 = ((tmp_188_fu_938_p3[0:0] == 1'b1) ? Range1_all_zeros_60_fu_932_p2 : Range1_all_ones_60_fu_926_p2);

assign select_ln934_61_fu_1056_p3 = ((tmp_191_fu_1048_p3[0:0] == 1'b1) ? Range1_all_zeros_61_fu_1042_p2 : Range1_all_ones_61_fu_1036_p2);

assign select_ln934_62_fu_1166_p3 = ((tmp_194_fu_1158_p3[0:0] == 1'b1) ? Range1_all_zeros_62_fu_1152_p2 : Range1_all_ones_62_fu_1146_p2);

assign select_ln934_63_fu_1276_p3 = ((tmp_197_fu_1268_p3[0:0] == 1'b1) ? Range1_all_zeros_63_fu_1262_p2 : Range1_all_ones_63_fu_1256_p2);

assign select_ln934_64_fu_1386_p3 = ((tmp_200_fu_1378_p3[0:0] == 1'b1) ? Range1_all_zeros_64_fu_1372_p2 : Range1_all_ones_64_fu_1366_p2);

assign select_ln934_65_fu_1496_p3 = ((tmp_203_fu_1488_p3[0:0] == 1'b1) ? Range1_all_zeros_65_fu_1482_p2 : Range1_all_ones_65_fu_1476_p2);

assign select_ln934_66_fu_1606_p3 = ((tmp_206_fu_1598_p3[0:0] == 1'b1) ? Range1_all_zeros_66_fu_1592_p2 : Range1_all_ones_66_fu_1586_p2);

assign select_ln934_67_fu_1716_p3 = ((tmp_209_fu_1708_p3[0:0] == 1'b1) ? Range1_all_zeros_67_fu_1702_p2 : Range1_all_ones_67_fu_1696_p2);

assign select_ln934_fu_286_p3 = ((tmp_fu_278_p3[0:0] == 1'b1) ? Range1_all_zeros_fu_272_p2 : Range1_all_ones_fu_266_p2);

assign tmp25_fu_256_p4 = {{p_read[15:10]}};

assign tmp_173_fu_388_p3 = p_Val2_114_fu_360_p2[32'd8];

assign tmp_176_fu_498_p3 = p_Val2_116_fu_470_p2[32'd8];

assign tmp_179_fu_608_p3 = p_Val2_118_fu_580_p2[32'd8];

assign tmp_182_fu_718_p3 = p_Val2_120_fu_690_p2[32'd8];

assign tmp_185_fu_828_p3 = p_Val2_122_fu_800_p2[32'd8];

assign tmp_188_fu_938_p3 = p_Val2_124_fu_910_p2[32'd8];

assign tmp_191_fu_1048_p3 = p_Val2_126_fu_1020_p2[32'd8];

assign tmp_194_fu_1158_p3 = p_Val2_128_fu_1130_p2[32'd8];

assign tmp_197_fu_1268_p3 = p_Val2_130_fu_1240_p2[32'd8];

assign tmp_200_fu_1378_p3 = p_Val2_132_fu_1350_p2[32'd8];

assign tmp_203_fu_1488_p3 = p_Val2_134_fu_1460_p2[32'd8];

assign tmp_206_fu_1598_p3 = p_Val2_136_fu_1570_p2[32'd8];

assign tmp_209_fu_1708_p3 = p_Val2_138_fu_1680_p2[32'd8];

assign tmp_30_fu_366_p4 = {{p_read1[15:10]}};

assign tmp_62_fu_586_p4 = {{p_read3[15:10]}};

assign tmp_63_fu_696_p4 = {{p_read4[15:10]}};

assign tmp_64_fu_806_p4 = {{p_read5[15:10]}};

assign tmp_65_fu_916_p4 = {{p_read6[15:10]}};

assign tmp_66_fu_1026_p4 = {{p_read7[15:10]}};

assign tmp_67_fu_1136_p4 = {{p_read8[15:10]}};

assign tmp_68_fu_1246_p4 = {{p_read9[15:10]}};

assign tmp_69_fu_1356_p4 = {{p_read11[15:10]}};

assign tmp_70_fu_1466_p4 = {{p_read12[15:10]}};

assign tmp_71_fu_1576_p4 = {{p_read13[15:10]}};

assign tmp_72_fu_1686_p4 = {{p_read14[15:10]}};

assign tmp_fu_278_p3 = p_Val2_112_fu_250_p2[32'd8];

assign tmp_s_fu_476_p4 = {{p_read2[15:10]}};

assign zext_ln423_55_fu_356_p1 = and_ln420_55_fu_350_p2;

assign zext_ln423_56_fu_466_p1 = and_ln420_56_fu_460_p2;

assign zext_ln423_57_fu_576_p1 = and_ln420_57_fu_570_p2;

assign zext_ln423_58_fu_686_p1 = and_ln420_58_fu_680_p2;

assign zext_ln423_59_fu_796_p1 = and_ln420_59_fu_790_p2;

assign zext_ln423_60_fu_906_p1 = and_ln420_60_fu_900_p2;

assign zext_ln423_61_fu_1016_p1 = and_ln420_61_fu_1010_p2;

assign zext_ln423_62_fu_1126_p1 = and_ln420_62_fu_1120_p2;

assign zext_ln423_63_fu_1236_p1 = and_ln420_63_fu_1230_p2;

assign zext_ln423_64_fu_1346_p1 = and_ln420_64_fu_1340_p2;

assign zext_ln423_65_fu_1456_p1 = and_ln420_65_fu_1450_p2;

assign zext_ln423_66_fu_1566_p1 = and_ln420_66_fu_1560_p2;

assign zext_ln423_67_fu_1676_p1 = and_ln420_67_fu_1670_p2;

assign zext_ln423_fu_246_p1 = and_ln420_fu_240_p2;

endmodule //tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config13_s
