-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config20_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config20_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv19_7FE22 : STD_LOGIC_VECTOR (18 downto 0) := "1111111111000100010";
    constant ap_const_lv19_25F : STD_LOGIC_VECTOR (18 downto 0) := "0000000001001011111";
    constant ap_const_lv18_189 : STD_LOGIC_VECTOR (17 downto 0) := "000000000110001001";
    constant ap_const_lv19_2F3 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001011110011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv11_F2 : STD_LOGIC_VECTOR (10 downto 0) := "00011110010";

attribute shreg_extract : string;
    signal tmp_reg_273 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_17_reg_278 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_reg_283 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_18_reg_288 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_177_fu_68_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_177_fu_68_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal r_V_fu_69_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_fu_69_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_178_fu_70_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_178_fu_70_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_176_fu_71_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_176_fu_71_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_69_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_176_fu_71_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_177_fu_68_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_178_fu_70_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln864_cast_fu_225_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln864_1_cast_fu_228_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln859_fu_237_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln859_fu_234_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln859_398_fu_247_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln859_102_fu_253_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln70_fu_231_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln859_399_fu_257_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln859_fu_263_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln859_101_fu_243_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln859_400_fu_267_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_int_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_176_fu_71_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_177_fu_68_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_178_fu_70_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal r_V_fu_69_p00 : STD_LOGIC_VECTOR (18 downto 0);

    component tau_nn_mul_9ns_10s_19_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component tau_nn_mul_9ns_11ns_19_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component tau_nn_mul_9ns_10ns_18_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    mul_9ns_10s_19_1_0_U614 : component tau_nn_mul_9ns_10s_19_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 10,
        dout_WIDTH => 19)
    port map (
        din0 => r_V_177_fu_68_p0,
        din1 => r_V_177_fu_68_p1,
        dout => r_V_177_fu_68_p2);

    mul_9ns_11ns_19_1_0_U615 : component tau_nn_mul_9ns_11ns_19_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => r_V_fu_69_p0,
        din1 => r_V_fu_69_p1,
        dout => r_V_fu_69_p2);

    mul_9ns_10ns_18_1_0_U616 : component tau_nn_mul_9ns_10ns_18_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 10,
        dout_WIDTH => 18)
    port map (
        din0 => r_V_178_fu_70_p0,
        din1 => r_V_178_fu_70_p1,
        dout => r_V_178_fu_70_p2);

    mul_9ns_11ns_19_1_0_U617 : component tau_nn_mul_9ns_11ns_19_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => r_V_176_fu_71_p0,
        din1 => r_V_176_fu_71_p1,
        dout => r_V_176_fu_71_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= add_ln859_400_fu_267_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1))) then
                tmp_17_reg_278 <= r_V_176_fu_71_p2(18 downto 8);
                tmp_18_reg_288 <= r_V_178_fu_70_p2(17 downto 8);
                tmp_reg_273 <= r_V_fu_69_p2(18 downto 8);
                trunc_ln_reg_283 <= r_V_177_fu_68_p2(18 downto 8);
            end if;
        end if;
    end process;
    add_ln859_398_fu_247_p2 <= std_logic_vector(unsigned(zext_ln859_fu_234_p1) + unsigned(ap_const_lv11_F2));
    add_ln859_399_fu_257_p2 <= std_logic_vector(unsigned(zext_ln859_102_fu_253_p1) + unsigned(sext_ln70_fu_231_p1));
    add_ln859_400_fu_267_p2 <= std_logic_vector(signed(sext_ln859_fu_263_p1) + signed(zext_ln859_101_fu_243_p1));
    add_ln859_fu_237_p2 <= std_logic_vector(unsigned(trunc_ln864_cast_fu_225_p1) + unsigned(trunc_ln864_1_cast_fu_228_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(add_ln859_400_fu_267_p2, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= add_ln859_400_fu_267_p2;
        else 
            ap_return <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    r_V_176_fu_71_p0 <= r_V_176_fu_71_p00(9 - 1 downto 0);
    r_V_176_fu_71_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read1),19));
    r_V_176_fu_71_p1 <= ap_const_lv19_2F3(11 - 1 downto 0);
    r_V_177_fu_68_p0 <= r_V_177_fu_68_p00(9 - 1 downto 0);
    r_V_177_fu_68_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read2),19));
    r_V_177_fu_68_p1 <= ap_const_lv19_7FE22(10 - 1 downto 0);
    r_V_178_fu_70_p0 <= r_V_178_fu_70_p00(9 - 1 downto 0);
    r_V_178_fu_70_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read3),18));
    r_V_178_fu_70_p1 <= ap_const_lv18_189(10 - 1 downto 0);
    r_V_fu_69_p0 <= r_V_fu_69_p00(9 - 1 downto 0);
    r_V_fu_69_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read),19));
    r_V_fu_69_p1 <= ap_const_lv19_25F(11 - 1 downto 0);
        sext_ln70_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_283),13));

        sext_ln859_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln859_399_fu_257_p2),14));

    trunc_ln864_1_cast_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_reg_278),12));
    trunc_ln864_cast_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_273),12));
    zext_ln859_101_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln859_fu_237_p2),14));
    zext_ln859_102_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln859_398_fu_247_p2),13));
    zext_ln859_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_reg_288),11));
end behav;
