// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [8:0] p_read;
input  [8:0] p_read1;
input  [8:0] p_read2;
input  [8:0] p_read3;
input  [8:0] p_read4;
input  [8:0] p_read5;
input  [8:0] p_read6;
input  [8:0] p_read7;
input  [8:0] p_read8;
input  [8:0] p_read9;
input  [8:0] p_read11;
input  [8:0] p_read12;
input  [8:0] p_read13;
input  [8:0] p_read14;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;

reg   [10:0] trunc_ln4_reg_7858;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] trunc_ln17_s_reg_7863;
reg   [9:0] trunc_ln17_107_reg_7868;
reg   [9:0] trunc_ln864_220_reg_7873;
reg  signed [9:0] trunc_ln864_222_reg_7878;
reg   [9:0] trunc_ln17_114_reg_7884;
reg   [10:0] trunc_ln864_226_reg_7889;
reg   [9:0] trunc_ln864_227_reg_7894;
reg   [9:0] trunc_ln864_228_reg_7899;
reg   [10:0] trunc_ln864_231_reg_7904;
reg   [10:0] trunc_ln864_232_reg_7909;
reg   [9:0] trunc_ln864_233_reg_7914;
reg   [9:0] trunc_ln17_120_reg_7919;
reg   [9:0] trunc_ln864_236_reg_7924;
wire   [10:0] add_ln859_fu_7387_p2;
reg   [10:0] add_ln859_reg_7929;
wire   [10:0] add_ln859_408_fu_7393_p2;
reg   [10:0] add_ln859_408_reg_7934;
wire   [10:0] add_ln859_409_fu_7399_p2;
reg   [10:0] add_ln859_409_reg_7939;
wire   [11:0] add_ln859_411_fu_7405_p2;
reg   [11:0] add_ln859_411_reg_7944;
wire   [10:0] add_ln859_415_fu_7411_p2;
reg   [10:0] add_ln859_415_reg_7949;
wire   [11:0] add_ln859_418_fu_7427_p2;
reg   [11:0] add_ln859_418_reg_7954;
wire   [9:0] add_ln859_420_fu_7433_p2;
reg   [9:0] add_ln859_420_reg_7959;
wire   [11:0] add_ln859_426_fu_7439_p2;
reg   [11:0] add_ln859_426_reg_7964;
wire   [12:0] add_ln859_431_fu_7455_p2;
reg   [12:0] add_ln859_431_reg_7969;
wire   [11:0] add_ln859_432_fu_7461_p2;
reg   [11:0] add_ln859_432_reg_7974;
wire   [11:0] add_ln859_436_fu_7467_p2;
reg   [11:0] add_ln859_436_reg_7979;
wire   [10:0] add_ln859_439_fu_7473_p2;
reg   [10:0] add_ln859_439_reg_7984;
wire   [8:0] r_V_192_fu_221_p0;
wire   [14:0] zext_ln864_171_fu_7028_p1;
wire  signed [5:0] r_V_192_fu_221_p1;
wire    ap_block_pp0_stage0;
wire   [8:0] mul_ln864_78_fu_222_p0;
wire   [14:0] zext_ln1319_179_fu_6712_p1;
wire   [6:0] mul_ln864_78_fu_222_p1;
wire   [8:0] mul_ln864_84_fu_225_p0;
wire   [5:0] mul_ln864_84_fu_225_p1;
wire   [8:0] r_V_183_fu_227_p0;
wire  signed [5:0] r_V_183_fu_227_p1;
wire   [8:0] mul_ln864_87_fu_229_p0;
wire   [14:0] zext_ln70_8_fu_7263_p1;
wire   [6:0] mul_ln864_87_fu_229_p1;
wire   [8:0] mul_ln864_fu_230_p0;
wire   [5:0] mul_ln864_fu_230_p1;
wire   [8:0] mul_ln864_86_fu_237_p0;
wire   [6:0] mul_ln864_86_fu_237_p1;
wire   [8:0] r_V_186_fu_238_p0;
wire  signed [6:0] r_V_186_fu_238_p1;
wire   [8:0] r_V_190_fu_241_p0;
wire   [14:0] zext_ln1319_185_fu_6932_p1;
wire  signed [5:0] r_V_190_fu_241_p1;
wire   [8:0] r_V_195_fu_242_p0;
wire  signed [6:0] r_V_195_fu_242_p1;
wire   [8:0] r_V_198_fu_243_p0;
wire  signed [5:0] r_V_198_fu_243_p1;
wire   [8:0] mul_ln864_81_fu_248_p0;
wire   [6:0] mul_ln864_81_fu_248_p1;
wire   [8:0] r_V_193_fu_255_p0;
wire   [14:0] zext_ln1319_187_fu_7130_p1;
wire  signed [5:0] r_V_193_fu_255_p1;
wire   [8:0] mul_ln864_82_fu_257_p0;
wire   [6:0] mul_ln864_82_fu_257_p1;
wire   [8:0] r_V_fu_259_p0;
wire  signed [6:0] r_V_fu_259_p1;
wire   [8:0] mul_ln864_79_fu_260_p0;
wire   [6:0] mul_ln864_79_fu_260_p1;
wire   [8:0] mul_ln864_80_fu_261_p0;
wire   [6:0] mul_ln864_80_fu_261_p1;
wire   [8:0] r_V_197_fu_263_p0;
wire  signed [5:0] r_V_197_fu_263_p1;
wire   [8:0] r_V_185_fu_265_p0;
wire  signed [5:0] r_V_185_fu_265_p1;
wire   [8:0] mul_ln864_83_fu_266_p0;
wire   [6:0] mul_ln864_83_fu_266_p1;
wire   [8:0] r_V_191_fu_267_p0;
wire  signed [6:0] r_V_191_fu_267_p1;
wire   [8:0] mul_ln864_85_fu_268_p0;
wire   [6:0] mul_ln864_85_fu_268_p1;
wire   [8:0] r_V_187_fu_269_p0;
wire  signed [5:0] r_V_187_fu_269_p1;
wire   [8:0] mul_ln864_77_fu_274_p0;
wire   [6:0] mul_ln864_77_fu_274_p1;
wire   [8:0] r_V_194_fu_276_p0;
wire  signed [5:0] r_V_194_fu_276_p1;
wire   [15:0] r_V_fu_259_p2;
wire   [10:0] trunc_ln_fu_6461_p4;
wire   [12:0] shl_ln_fu_6475_p3;
wire   [13:0] zext_ln1319_175_fu_6483_p1;
wire   [13:0] sub_ln1319_fu_6487_p2;
wire   [9:0] shl_ln1319_s_fu_6497_p3;
wire  signed [14:0] sext_ln1319_fu_6493_p1;
wire   [14:0] zext_ln1319_176_fu_6505_p1;
wire   [14:0] r_V_182_fu_6509_p2;
wire   [9:0] trunc_ln864_s_fu_6515_p4;
wire   [14:0] shl_ln2_fu_6529_p3;
wire   [15:0] zext_ln864_fu_6537_p1;
wire   [15:0] zext_ln864_162_fu_6541_p1;
wire   [15:0] add_ln864_fu_6545_p2;
wire   [13:0] mul_ln864_fu_230_p2;
wire   [13:0] shl_ln864_s_fu_6581_p3;
wire   [11:0] shl_ln864_83_fu_6593_p3;
wire   [14:0] zext_ln864_164_fu_6589_p1;
wire   [14:0] zext_ln864_165_fu_6601_p1;
wire   [14:0] sub_ln864_fu_6605_p2;
wire   [9:0] trunc_ln864_217_fu_6611_p4;
wire  signed [10:0] sext_ln17_fu_6621_p1;
wire   [14:0] r_V_183_fu_227_p2;
wire   [9:0] trunc_ln864_218_fu_6629_p4;
wire   [14:0] mul_ln864_77_fu_274_p2;
wire   [12:0] shl_ln1319_79_fu_6658_p3;
wire   [13:0] zext_ln1319_177_fu_6666_p1;
wire   [13:0] sub_ln1319_108_fu_6670_p2;
wire   [10:0] shl_ln1319_80_fu_6680_p3;
wire  signed [14:0] sext_ln1319_27_fu_6676_p1;
wire   [14:0] zext_ln1319_178_fu_6688_p1;
wire   [14:0] r_V_184_fu_6692_p2;
wire   [9:0] trunc_ln864_219_fu_6698_p4;
wire   [14:0] r_V_185_fu_265_p2;
wire   [14:0] mul_ln864_78_fu_222_p2;
wire   [9:0] trunc_ln17_108_fu_6730_p4;
wire   [14:0] mul_ln864_79_fu_260_p2;
wire   [9:0] trunc_ln17_109_fu_6744_p4;
wire   [14:0] mul_ln864_80_fu_261_p2;
wire   [9:0] trunc_ln17_110_fu_6758_p4;
wire   [15:0] r_V_186_fu_238_p2;
wire   [10:0] trunc_ln864_221_fu_6777_p4;
wire   [14:0] mul_ln864_81_fu_248_p2;
wire   [9:0] trunc_ln17_111_fu_6796_p4;
wire   [14:0] shl_ln864_84_fu_6810_p3;
wire   [12:0] shl_ln864_85_fu_6822_p3;
wire   [15:0] zext_ln864_168_fu_6818_p1;
wire   [15:0] zext_ln864_169_fu_6830_p1;
wire   [15:0] sub_ln864_43_fu_6834_p2;
wire   [10:0] trunc_ln17_112_fu_6840_p4;
wire   [14:0] r_V_187_fu_269_p2;
wire   [14:0] shl_ln1319_81_fu_6874_p3;
wire   [12:0] shl_ln1319_82_fu_6886_p3;
wire   [15:0] zext_ln1319_184_fu_6894_p1;
wire   [15:0] zext_ln1319_183_fu_6882_p1;
wire   [15:0] r_V_188_fu_6898_p2;
wire   [10:0] trunc_ln864_223_fu_6904_p4;
wire   [14:0] mul_ln864_82_fu_257_p2;
wire   [9:0] trunc_ln17_113_fu_6918_p4;
wire   [13:0] tmp_fu_6938_p3;
wire   [14:0] zext_ln1319_186_fu_6946_p1;
wire   [14:0] r_V_189_fu_6950_p2;
wire   [9:0] trunc_ln864_224_fu_6956_p4;
wire   [14:0] r_V_190_fu_241_p2;
wire   [9:0] trunc_ln864_225_fu_6970_p4;
wire   [14:0] mul_ln864_83_fu_266_p2;
wire   [13:0] mul_ln864_84_fu_225_p2;
wire   [8:0] trunc_ln17_115_fu_7004_p4;
wire   [15:0] r_V_191_fu_267_p2;
wire   [13:0] shl_ln864_86_fu_7034_p3;
wire   [14:0] mul_ln864_85_fu_268_p2;
wire   [9:0] trunc_ln17_116_fu_7046_p4;
wire   [9:0] shl_ln864_87_fu_7060_p3;
wire   [14:0] zext_ln864_172_fu_7042_p1;
wire   [14:0] zext_ln864_173_fu_7068_p1;
wire   [14:0] add_ln864_46_fu_7072_p2;
wire   [11:0] shl_ln864_88_fu_7088_p3;
wire   [14:0] zext_ln864_174_fu_7096_p1;
wire   [14:0] add_ln864_47_fu_7100_p2;
wire   [9:0] trunc_ln17_118_fu_7106_p4;
wire   [14:0] r_V_192_fu_221_p2;
wire   [14:0] r_V_193_fu_255_p2;
wire   [13:0] shl_ln864_89_fu_7146_p3;
wire   [11:0] shl_ln864_90_fu_7158_p3;
wire   [14:0] zext_ln864_175_fu_7154_p1;
wire   [14:0] zext_ln864_176_fu_7166_p1;
wire   [14:0] sub_ln864_44_fu_7170_p2;
wire   [9:0] trunc_ln864_229_fu_7176_p4;
wire  signed [10:0] sext_ln17_43_fu_7186_p1;
wire   [14:0] r_V_194_fu_276_p2;
wire   [9:0] trunc_ln864_230_fu_7194_p4;
wire   [15:0] r_V_195_fu_242_p2;
wire   [14:0] shl_ln1319_83_fu_7223_p3;
wire   [11:0] shl_ln1319_84_fu_7235_p3;
wire   [15:0] zext_ln1319_190_fu_7243_p1;
wire   [15:0] zext_ln1319_189_fu_7231_p1;
wire   [15:0] r_V_196_fu_7247_p2;
wire   [13:0] shl_ln864_91_fu_7270_p3;
wire   [14:0] mul_ln864_86_fu_237_p2;
wire   [9:0] trunc_ln17_119_fu_7282_p4;
wire   [14:0] zext_ln864_177_fu_7278_p1;
wire   [14:0] sub_ln864_45_fu_7296_p2;
wire   [14:0] mul_ln864_87_fu_229_p2;
wire   [11:0] shl_ln864_92_fu_7322_p3;
wire   [14:0] zext_ln864_179_fu_7330_p1;
wire   [14:0] sub_ln864_46_fu_7334_p2;
wire   [9:0] trunc_ln864_234_fu_7340_p4;
wire  signed [10:0] sext_ln17_44_fu_7350_p1;
wire   [14:0] r_V_197_fu_263_p2;
wire   [9:0] trunc_ln864_235_fu_7358_p4;
wire   [14:0] r_V_198_fu_243_p2;
wire   [10:0] zext_ln17_168_fu_6806_p1;
wire   [10:0] zext_ln17_170_fu_6928_p1;
wire   [10:0] zext_ln17_167_fu_6768_p1;
wire   [10:0] zext_ln17_173_fu_7116_p1;
wire  signed [10:0] sext_ln864_fu_6525_p1;
wire  signed [10:0] sext_ln70_22_fu_6708_p1;
wire  signed [11:0] sext_ln864_91_fu_6914_p1;
wire  signed [11:0] sext_ln864_92_fu_6980_p1;
wire   [10:0] zext_ln17_172_fu_7056_p1;
wire   [10:0] zext_ln17_175_fu_7292_p1;
wire  signed [10:0] sext_ln1319_80_fu_6966_p1;
wire   [10:0] add_ln859_417_fu_7417_p2;
wire  signed [11:0] sext_ln859_231_fu_7423_p1;
wire  signed [11:0] sext_ln1319_79_fu_6471_p1;
wire   [9:0] zext_ln17_171_fu_7014_p1;
wire   [9:0] trunc_ln17_117_fu_7078_p4;
wire   [11:0] zext_ln17_163_fu_6625_p1;
wire   [11:0] zext_ln17_165_fu_6740_p1;
wire   [11:0] zext_ln17_174_fu_7190_p1;
wire   [11:0] zext_ln17_176_fu_7354_p1;
wire   [11:0] add_ln859_430_fu_7445_p2;
wire   [12:0] zext_ln859_107_fu_7451_p1;
wire   [12:0] zext_ln17_166_fu_6754_p1;
wire  signed [11:0] sext_ln70_fu_6639_p1;
wire  signed [11:0] sext_ln864_90_fu_6787_p1;
wire   [11:0] zext_ln17_169_fu_6850_p1;
wire  signed [10:0] sext_ln70_27_fu_7204_p1;
wire  signed [10:0] sext_ln70_29_fu_7368_p1;
wire  signed [10:0] sext_ln864_94_fu_7515_p1;
wire   [11:0] zext_ln859_fu_7528_p1;
wire   [11:0] zext_ln17_fu_7479_p1;
wire   [11:0] add_ln859_404_fu_7531_p2;
wire  signed [10:0] sext_ln70_26_fu_7503_p1;
wire   [10:0] add_ln859_405_fu_7541_p2;
wire  signed [11:0] sext_ln859_223_fu_7547_p1;
wire   [11:0] zext_ln70_10_fu_7497_p1;
wire   [11:0] add_ln859_406_fu_7551_p2;
wire  signed [13:0] sext_ln859_224_fu_7557_p1;
wire   [13:0] zext_ln859_100_fu_7537_p1;
wire   [13:0] add_ln859_407_fu_7561_p2;
wire  signed [12:0] sext_ln859_225_fu_7574_p1;
wire   [12:0] zext_ln859_103_fu_7571_p1;
wire   [12:0] add_ln859_410_fu_7577_p2;
wire  signed [11:0] sext_ln70_28_fu_7512_p1;
wire   [11:0] add_ln859_412_fu_7590_p2;
wire  signed [12:0] sext_ln859_228_fu_7596_p1;
wire  signed [12:0] sext_ln859_227_fu_7587_p1;
wire   [12:0] add_ln859_413_fu_7600_p2;
wire  signed [13:0] sext_ln859_229_fu_7606_p1;
wire  signed [13:0] sext_ln859_226_fu_7583_p1;
wire   [13:0] add_ln859_414_fu_7610_p2;
wire   [11:0] zext_ln859_102_fu_7620_p1;
wire   [11:0] zext_ln17_164_fu_7485_p1;
wire   [11:0] add_ln859_416_fu_7623_p2;
wire  signed [13:0] sext_ln859_232_fu_7633_p1;
wire   [13:0] zext_ln859_105_fu_7629_p1;
wire   [13:0] add_ln859_419_fu_7636_p2;
wire   [10:0] zext_ln859_104_fu_7646_p1;
wire   [10:0] zext_ln17_162_fu_7482_p1;
wire   [10:0] add_ln859_421_fu_7649_p2;
wire   [12:0] zext_ln864_178_fu_7518_p1;
wire  signed [12:0] sext_ln864_89_fu_7488_p1;
wire  signed [11:0] sext_ln1319_81_fu_7509_p1;
wire   [11:0] add_ln859_423_fu_7665_p2;
wire  signed [12:0] sext_ln859_233_fu_7671_p1;
wire   [12:0] add_ln859_422_fu_7659_p2;
wire   [12:0] add_ln859_424_fu_7675_p2;
wire  signed [13:0] sext_ln859_234_fu_7681_p1;
wire   [13:0] zext_ln859_108_fu_7655_p1;
wire   [13:0] add_ln859_425_fu_7685_p2;
wire  signed [10:0] sext_ln864_93_fu_7506_p1;
wire   [10:0] add_ln859_427_fu_7698_p2;
wire  signed [11:0] sext_ln859_235_fu_7704_p1;
wire   [11:0] zext_ln864_180_fu_7522_p1;
wire   [11:0] add_ln859_428_fu_7708_p2;
wire  signed [13:0] sext_ln859_236_fu_7714_p1;
wire   [13:0] zext_ln859_106_fu_7695_p1;
wire   [13:0] add_ln859_429_fu_7718_p2;
wire  signed [10:0] sext_ln70_24_fu_7494_p1;
wire   [10:0] add_ln859_433_fu_7734_p2;
wire  signed [12:0] sext_ln859_238_fu_7740_p1;
wire  signed [12:0] sext_ln859_237_fu_7731_p1;
wire   [12:0] add_ln859_434_fu_7744_p2;
wire  signed [13:0] sext_ln859_239_fu_7750_p1;
wire   [13:0] zext_ln859_109_fu_7728_p1;
wire   [13:0] add_ln859_435_fu_7754_p2;
wire  signed [11:0] sext_ln70_23_fu_7491_p1;
wire  signed [11:0] sext_ln70_25_fu_7500_p1;
wire   [11:0] add_ln859_437_fu_7767_p2;
wire  signed [13:0] sext_ln859_241_fu_7773_p1;
wire   [13:0] zext_ln859_110_fu_7764_p1;
wire  signed [10:0] sext_ln859_222_fu_7525_p1;
wire   [10:0] add_ln859_440_fu_7786_p2;
wire  signed [11:0] sext_ln859_243_fu_7792_p1;
wire  signed [11:0] sext_ln859_242_fu_7783_p1;
wire   [11:0] add_ln859_441_fu_7796_p2;
wire  signed [13:0] sext_ln859_244_fu_7802_p1;
wire   [13:0] add_ln859_438_fu_7777_p2;
wire   [13:0] add_ln859_442_fu_7806_p2;
wire  signed [15:0] sext_ln859_126_fu_7642_p1;
wire  signed [15:0] sext_ln859_128_fu_7691_p1;
wire  signed [15:0] sext_ln859_129_fu_7724_p1;
wire  signed [15:0] sext_ln859_240_fu_7760_p1;
wire  signed [15:0] sext_ln859_230_fu_7616_p1;
wire  signed [15:0] sext_ln859_fu_7567_p1;
wire  signed [15:0] add_ln859_442_cast_fu_7812_p1;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
wire   [14:0] mul_ln864_77_fu_274_p00;
wire   [14:0] mul_ln864_81_fu_248_p00;
wire   [14:0] mul_ln864_82_fu_257_p00;
wire   [13:0] mul_ln864_84_fu_225_p00;
wire   [13:0] mul_ln864_fu_230_p00;
wire   [14:0] r_V_183_fu_227_p00;
wire   [15:0] r_V_186_fu_238_p00;
wire   [14:0] r_V_187_fu_269_p00;
wire   [15:0] r_V_191_fu_267_p00;
wire   [15:0] r_V_195_fu_242_p00;
wire   [14:0] r_V_198_fu_243_p00;
wire   [15:0] r_V_fu_259_p00;

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U556(
    .din0(r_V_192_fu_221_p0),
    .din1(r_V_192_fu_221_p1),
    .dout(r_V_192_fu_221_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U557(
    .din0(mul_ln864_78_fu_222_p0),
    .din1(mul_ln864_78_fu_222_p1),
    .dout(mul_ln864_78_fu_222_p2)
);

tau_nn_mul_9ns_6ns_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_0_U558(
    .din0(mul_ln864_84_fu_225_p0),
    .din1(mul_ln864_84_fu_225_p1),
    .dout(mul_ln864_84_fu_225_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U559(
    .din0(r_V_183_fu_227_p0),
    .din1(r_V_183_fu_227_p1),
    .dout(r_V_183_fu_227_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U560(
    .din0(mul_ln864_87_fu_229_p0),
    .din1(mul_ln864_87_fu_229_p1),
    .dout(mul_ln864_87_fu_229_p2)
);

tau_nn_mul_9ns_6ns_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_0_U561(
    .din0(mul_ln864_fu_230_p0),
    .din1(mul_ln864_fu_230_p1),
    .dout(mul_ln864_fu_230_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U562(
    .din0(mul_ln864_86_fu_237_p0),
    .din1(mul_ln864_86_fu_237_p1),
    .dout(mul_ln864_86_fu_237_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U563(
    .din0(r_V_186_fu_238_p0),
    .din1(r_V_186_fu_238_p1),
    .dout(r_V_186_fu_238_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U564(
    .din0(r_V_190_fu_241_p0),
    .din1(r_V_190_fu_241_p1),
    .dout(r_V_190_fu_241_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U565(
    .din0(r_V_195_fu_242_p0),
    .din1(r_V_195_fu_242_p1),
    .dout(r_V_195_fu_242_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U566(
    .din0(r_V_198_fu_243_p0),
    .din1(r_V_198_fu_243_p1),
    .dout(r_V_198_fu_243_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U567(
    .din0(mul_ln864_81_fu_248_p0),
    .din1(mul_ln864_81_fu_248_p1),
    .dout(mul_ln864_81_fu_248_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U568(
    .din0(r_V_193_fu_255_p0),
    .din1(r_V_193_fu_255_p1),
    .dout(r_V_193_fu_255_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U569(
    .din0(mul_ln864_82_fu_257_p0),
    .din1(mul_ln864_82_fu_257_p1),
    .dout(mul_ln864_82_fu_257_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U570(
    .din0(r_V_fu_259_p0),
    .din1(r_V_fu_259_p1),
    .dout(r_V_fu_259_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U571(
    .din0(mul_ln864_79_fu_260_p0),
    .din1(mul_ln864_79_fu_260_p1),
    .dout(mul_ln864_79_fu_260_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U572(
    .din0(mul_ln864_80_fu_261_p0),
    .din1(mul_ln864_80_fu_261_p1),
    .dout(mul_ln864_80_fu_261_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U573(
    .din0(r_V_197_fu_263_p0),
    .din1(r_V_197_fu_263_p1),
    .dout(r_V_197_fu_263_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U574(
    .din0(r_V_185_fu_265_p0),
    .din1(r_V_185_fu_265_p1),
    .dout(r_V_185_fu_265_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U575(
    .din0(mul_ln864_83_fu_266_p0),
    .din1(mul_ln864_83_fu_266_p1),
    .dout(mul_ln864_83_fu_266_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U576(
    .din0(r_V_191_fu_267_p0),
    .din1(r_V_191_fu_267_p1),
    .dout(r_V_191_fu_267_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U577(
    .din0(mul_ln864_85_fu_268_p0),
    .din1(mul_ln864_85_fu_268_p1),
    .dout(mul_ln864_85_fu_268_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U578(
    .din0(r_V_187_fu_269_p0),
    .din1(r_V_187_fu_269_p1),
    .dout(r_V_187_fu_269_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U579(
    .din0(mul_ln864_77_fu_274_p0),
    .din1(mul_ln864_77_fu_274_p1),
    .dout(mul_ln864_77_fu_274_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U580(
    .din0(r_V_194_fu_276_p0),
    .din1(r_V_194_fu_276_p1),
    .dout(r_V_194_fu_276_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln859_408_reg_7934 <= add_ln859_408_fu_7393_p2;
        add_ln859_409_reg_7939 <= add_ln859_409_fu_7399_p2;
        add_ln859_411_reg_7944 <= add_ln859_411_fu_7405_p2;
        add_ln859_415_reg_7949 <= add_ln859_415_fu_7411_p2;
        add_ln859_418_reg_7954 <= add_ln859_418_fu_7427_p2;
        add_ln859_420_reg_7959 <= add_ln859_420_fu_7433_p2;
        add_ln859_426_reg_7964 <= add_ln859_426_fu_7439_p2;
        add_ln859_431_reg_7969 <= add_ln859_431_fu_7455_p2;
        add_ln859_432_reg_7974 <= add_ln859_432_fu_7461_p2;
        add_ln859_436_reg_7979 <= add_ln859_436_fu_7467_p2;
        add_ln859_439_reg_7984 <= add_ln859_439_fu_7473_p2;
        add_ln859_reg_7929 <= add_ln859_fu_7387_p2;
        trunc_ln17_107_reg_7868 <= {{mul_ln864_77_fu_274_p2[14:5]}};
        trunc_ln17_114_reg_7884 <= {{mul_ln864_83_fu_266_p2[14:5]}};
        trunc_ln17_120_reg_7919 <= {{mul_ln864_87_fu_229_p2[14:5]}};
        trunc_ln17_s_reg_7863 <= {{mul_ln864_fu_230_p2[13:5]}};
        trunc_ln4_reg_7858 <= {{add_ln864_fu_6545_p2[15:5]}};
        trunc_ln864_220_reg_7873 <= {{r_V_185_fu_265_p2[14:5]}};
        trunc_ln864_222_reg_7878 <= {{r_V_187_fu_269_p2[14:5]}};
        trunc_ln864_226_reg_7889 <= {{r_V_191_fu_267_p2[15:5]}};
        trunc_ln864_227_reg_7894 <= {{r_V_192_fu_221_p2[14:5]}};
        trunc_ln864_228_reg_7899 <= {{r_V_193_fu_255_p2[14:5]}};
        trunc_ln864_231_reg_7904 <= {{r_V_195_fu_242_p2[15:5]}};
        trunc_ln864_232_reg_7909 <= {{r_V_196_fu_7247_p2[15:5]}};
        trunc_ln864_233_reg_7914 <= {{sub_ln864_45_fu_7296_p2[14:5]}};
        trunc_ln864_236_reg_7924 <= {{r_V_198_fu_243_p2[14:5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln859_126_fu_7642_p1;
        ap_return_1_int_reg <= sext_ln859_128_fu_7691_p1;
        ap_return_2_int_reg <= sext_ln859_129_fu_7724_p1;
        ap_return_3_int_reg <= sext_ln859_240_fu_7760_p1;
        ap_return_4_int_reg <= sext_ln859_230_fu_7616_p1;
        ap_return_5_int_reg <= sext_ln859_fu_7567_p1;
        ap_return_6_int_reg <= add_ln859_442_cast_fu_7812_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln859_126_fu_7642_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln859_128_fu_7691_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln859_129_fu_7724_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln859_240_fu_7760_p1;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln859_230_fu_7616_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln859_fu_7567_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln859_442_cast_fu_7812_p1;
    end else begin
        ap_return_6 = 'bx;
    end
end

assign add_ln859_404_fu_7531_p2 = (zext_ln859_fu_7528_p1 + zext_ln17_fu_7479_p1);

assign add_ln859_405_fu_7541_p2 = ($signed(sext_ln70_26_fu_7503_p1) + $signed(11'd16));

assign add_ln859_406_fu_7551_p2 = ($signed(sext_ln859_223_fu_7547_p1) + $signed(zext_ln70_10_fu_7497_p1));

assign add_ln859_407_fu_7561_p2 = ($signed(sext_ln859_224_fu_7557_p1) + $signed(zext_ln859_100_fu_7537_p1));

assign add_ln859_408_fu_7393_p2 = (zext_ln17_167_fu_6768_p1 + zext_ln17_173_fu_7116_p1);

assign add_ln859_409_fu_7399_p2 = ($signed(sext_ln864_fu_6525_p1) + $signed(sext_ln70_22_fu_6708_p1));

assign add_ln859_410_fu_7577_p2 = ($signed(sext_ln859_225_fu_7574_p1) + $signed(zext_ln859_103_fu_7571_p1));

assign add_ln859_411_fu_7405_p2 = ($signed(sext_ln864_91_fu_6914_p1) + $signed(sext_ln864_92_fu_6980_p1));

assign add_ln859_412_fu_7590_p2 = ($signed(sext_ln70_28_fu_7512_p1) + $signed(12'd208));

assign add_ln859_413_fu_7600_p2 = ($signed(sext_ln859_228_fu_7596_p1) + $signed(sext_ln859_227_fu_7587_p1));

assign add_ln859_414_fu_7610_p2 = ($signed(sext_ln859_229_fu_7606_p1) + $signed(sext_ln859_226_fu_7583_p1));

assign add_ln859_415_fu_7411_p2 = (zext_ln17_172_fu_7056_p1 + zext_ln17_175_fu_7292_p1);

assign add_ln859_416_fu_7623_p2 = (zext_ln859_102_fu_7620_p1 + zext_ln17_164_fu_7485_p1);

assign add_ln859_417_fu_7417_p2 = ($signed(sext_ln1319_80_fu_6966_p1) + $signed(11'd16));

assign add_ln859_418_fu_7427_p2 = ($signed(sext_ln859_231_fu_7423_p1) + $signed(sext_ln1319_79_fu_6471_p1));

assign add_ln859_419_fu_7636_p2 = ($signed(sext_ln859_232_fu_7633_p1) + $signed(zext_ln859_105_fu_7629_p1));

assign add_ln859_420_fu_7433_p2 = (zext_ln17_171_fu_7014_p1 + trunc_ln17_117_fu_7078_p4);

assign add_ln859_421_fu_7649_p2 = (zext_ln859_104_fu_7646_p1 + zext_ln17_162_fu_7482_p1);

assign add_ln859_422_fu_7659_p2 = ($signed(zext_ln864_178_fu_7518_p1) + $signed(sext_ln864_89_fu_7488_p1));

assign add_ln859_423_fu_7665_p2 = ($signed(sext_ln1319_81_fu_7509_p1) + $signed(12'd48));

assign add_ln859_424_fu_7675_p2 = ($signed(sext_ln859_233_fu_7671_p1) + $signed(add_ln859_422_fu_7659_p2));

assign add_ln859_425_fu_7685_p2 = ($signed(sext_ln859_234_fu_7681_p1) + $signed(zext_ln859_108_fu_7655_p1));

assign add_ln859_426_fu_7439_p2 = (zext_ln17_163_fu_6625_p1 + zext_ln17_165_fu_6740_p1);

assign add_ln859_427_fu_7698_p2 = ($signed(sext_ln864_93_fu_7506_p1) + $signed(11'd2032));

assign add_ln859_428_fu_7708_p2 = ($signed(sext_ln859_235_fu_7704_p1) + $signed(zext_ln864_180_fu_7522_p1));

assign add_ln859_429_fu_7718_p2 = ($signed(sext_ln859_236_fu_7714_p1) + $signed(zext_ln859_106_fu_7695_p1));

assign add_ln859_430_fu_7445_p2 = (zext_ln17_174_fu_7190_p1 + zext_ln17_176_fu_7354_p1);

assign add_ln859_431_fu_7455_p2 = (zext_ln859_107_fu_7451_p1 + zext_ln17_166_fu_6754_p1);

assign add_ln859_432_fu_7461_p2 = ($signed(sext_ln70_fu_6639_p1) + $signed(sext_ln864_90_fu_6787_p1));

assign add_ln859_433_fu_7734_p2 = ($signed(sext_ln70_24_fu_7494_p1) + $signed(11'd48));

assign add_ln859_434_fu_7744_p2 = ($signed(sext_ln859_238_fu_7740_p1) + $signed(sext_ln859_237_fu_7731_p1));

assign add_ln859_435_fu_7754_p2 = ($signed(sext_ln859_239_fu_7750_p1) + $signed(zext_ln859_109_fu_7728_p1));

assign add_ln859_436_fu_7467_p2 = (zext_ln17_163_fu_6625_p1 + zext_ln17_169_fu_6850_p1);

assign add_ln859_437_fu_7767_p2 = ($signed(sext_ln70_23_fu_7491_p1) + $signed(sext_ln70_25_fu_7500_p1));

assign add_ln859_438_fu_7777_p2 = ($signed(sext_ln859_241_fu_7773_p1) + $signed(zext_ln859_110_fu_7764_p1));

assign add_ln859_439_fu_7473_p2 = ($signed(sext_ln70_27_fu_7204_p1) + $signed(sext_ln70_29_fu_7368_p1));

assign add_ln859_440_fu_7786_p2 = ($signed(sext_ln859_222_fu_7525_p1) + $signed(11'd256));

assign add_ln859_441_fu_7796_p2 = ($signed(sext_ln859_243_fu_7792_p1) + $signed(sext_ln859_242_fu_7783_p1));

assign add_ln859_442_cast_fu_7812_p1 = $signed(add_ln859_442_fu_7806_p2);

assign add_ln859_442_fu_7806_p2 = ($signed(sext_ln859_244_fu_7802_p1) + $signed(add_ln859_438_fu_7777_p2));

assign add_ln859_fu_7387_p2 = (zext_ln17_168_fu_6806_p1 + zext_ln17_170_fu_6928_p1);

assign add_ln864_46_fu_7072_p2 = (zext_ln864_172_fu_7042_p1 + zext_ln864_173_fu_7068_p1);

assign add_ln864_47_fu_7100_p2 = (zext_ln864_172_fu_7042_p1 + zext_ln864_174_fu_7096_p1);

assign add_ln864_fu_6545_p2 = (zext_ln864_fu_6537_p1 + zext_ln864_162_fu_6541_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln864_77_fu_274_p0 = mul_ln864_77_fu_274_p00;

assign mul_ln864_77_fu_274_p00 = p_read2;

assign mul_ln864_77_fu_274_p1 = 15'd53;

assign mul_ln864_78_fu_222_p0 = zext_ln1319_179_fu_6712_p1;

assign mul_ln864_78_fu_222_p1 = 15'd51;

assign mul_ln864_79_fu_260_p0 = zext_ln1319_179_fu_6712_p1;

assign mul_ln864_79_fu_260_p1 = 15'd41;

assign mul_ln864_80_fu_261_p0 = zext_ln1319_179_fu_6712_p1;

assign mul_ln864_80_fu_261_p1 = 15'd35;

assign mul_ln864_81_fu_248_p0 = mul_ln864_81_fu_248_p00;

assign mul_ln864_81_fu_248_p00 = p_read4;

assign mul_ln864_81_fu_248_p1 = 15'd55;

assign mul_ln864_82_fu_257_p0 = mul_ln864_82_fu_257_p00;

assign mul_ln864_82_fu_257_p00 = p_read6;

assign mul_ln864_82_fu_257_p1 = 15'd41;

assign mul_ln864_83_fu_266_p0 = zext_ln1319_185_fu_6932_p1;

assign mul_ln864_83_fu_266_p1 = 15'd50;

assign mul_ln864_84_fu_225_p0 = mul_ln864_84_fu_225_p00;

assign mul_ln864_84_fu_225_p00 = p_read8;

assign mul_ln864_84_fu_225_p1 = 14'd21;

assign mul_ln864_85_fu_268_p0 = zext_ln864_171_fu_7028_p1;

assign mul_ln864_85_fu_268_p1 = 15'd41;

assign mul_ln864_86_fu_237_p0 = zext_ln70_8_fu_7263_p1;

assign mul_ln864_86_fu_237_p1 = 15'd46;

assign mul_ln864_87_fu_229_p0 = zext_ln70_8_fu_7263_p1;

assign mul_ln864_87_fu_229_p1 = 15'd52;

assign mul_ln864_fu_230_p0 = mul_ln864_fu_230_p00;

assign mul_ln864_fu_230_p00 = p_read1;

assign mul_ln864_fu_230_p1 = 14'd23;

assign r_V_182_fu_6509_p2 = ($signed(sext_ln1319_fu_6493_p1) - $signed(zext_ln1319_176_fu_6505_p1));

assign r_V_183_fu_227_p0 = r_V_183_fu_227_p00;

assign r_V_183_fu_227_p00 = p_read1;

assign r_V_183_fu_227_p1 = 15'd32741;

assign r_V_184_fu_6692_p2 = ($signed(sext_ln1319_27_fu_6676_p1) - $signed(zext_ln1319_178_fu_6688_p1));

assign r_V_185_fu_265_p0 = zext_ln1319_179_fu_6712_p1;

assign r_V_185_fu_265_p1 = 15'd32742;

assign r_V_186_fu_238_p0 = r_V_186_fu_238_p00;

assign r_V_186_fu_238_p00 = p_read4;

assign r_V_186_fu_238_p1 = 16'd65479;

assign r_V_187_fu_269_p0 = r_V_187_fu_269_p00;

assign r_V_187_fu_269_p00 = p_read5;

assign r_V_187_fu_269_p1 = 15'd32747;

assign r_V_188_fu_6898_p2 = (zext_ln1319_184_fu_6894_p1 - zext_ln1319_183_fu_6882_p1);

assign r_V_189_fu_6950_p2 = (zext_ln1319_185_fu_6932_p1 - zext_ln1319_186_fu_6946_p1);

assign r_V_190_fu_241_p0 = zext_ln1319_185_fu_6932_p1;

assign r_V_190_fu_241_p1 = 15'd32741;

assign r_V_191_fu_267_p0 = r_V_191_fu_267_p00;

assign r_V_191_fu_267_p00 = p_read8;

assign r_V_191_fu_267_p1 = 16'd65501;

assign r_V_192_fu_221_p0 = zext_ln864_171_fu_7028_p1;

assign r_V_192_fu_221_p1 = 15'd32749;

assign r_V_193_fu_255_p0 = zext_ln1319_187_fu_7130_p1;

assign r_V_193_fu_255_p1 = 15'd32749;

assign r_V_194_fu_276_p0 = zext_ln1319_187_fu_7130_p1;

assign r_V_194_fu_276_p1 = 15'd32747;

assign r_V_195_fu_242_p0 = r_V_195_fu_242_p00;

assign r_V_195_fu_242_p00 = p_read12;

assign r_V_195_fu_242_p1 = 16'd65493;

assign r_V_196_fu_7247_p2 = (zext_ln1319_190_fu_7243_p1 - zext_ln1319_189_fu_7231_p1);

assign r_V_197_fu_263_p0 = zext_ln70_8_fu_7263_p1;

assign r_V_197_fu_263_p1 = 15'd32743;

assign r_V_198_fu_243_p0 = r_V_198_fu_243_p00;

assign r_V_198_fu_243_p00 = p_read14;

assign r_V_198_fu_243_p1 = 15'd32743;

assign r_V_fu_259_p0 = r_V_fu_259_p00;

assign r_V_fu_259_p00 = p_read;

assign r_V_fu_259_p1 = 16'd65482;

assign sext_ln1319_27_fu_6676_p1 = $signed(sub_ln1319_108_fu_6670_p2);

assign sext_ln1319_79_fu_6471_p1 = $signed(trunc_ln_fu_6461_p4);

assign sext_ln1319_80_fu_6966_p1 = $signed(trunc_ln864_224_fu_6956_p4);

assign sext_ln1319_81_fu_7509_p1 = $signed(trunc_ln864_231_reg_7904);

assign sext_ln1319_fu_6493_p1 = $signed(sub_ln1319_fu_6487_p2);

assign sext_ln17_43_fu_7186_p1 = $signed(trunc_ln864_229_fu_7176_p4);

assign sext_ln17_44_fu_7350_p1 = $signed(trunc_ln864_234_fu_7340_p4);

assign sext_ln17_fu_6621_p1 = $signed(trunc_ln864_217_fu_6611_p4);

assign sext_ln70_22_fu_6708_p1 = $signed(trunc_ln864_219_fu_6698_p4);

assign sext_ln70_23_fu_7491_p1 = trunc_ln864_222_reg_7878;

assign sext_ln70_24_fu_7494_p1 = trunc_ln864_222_reg_7878;

assign sext_ln70_25_fu_7500_p1 = $signed(trunc_ln864_226_reg_7889);

assign sext_ln70_26_fu_7503_p1 = $signed(trunc_ln864_227_reg_7894);

assign sext_ln70_27_fu_7204_p1 = $signed(trunc_ln864_230_fu_7194_p4);

assign sext_ln70_28_fu_7512_p1 = $signed(trunc_ln864_232_reg_7909);

assign sext_ln70_29_fu_7368_p1 = $signed(trunc_ln864_235_fu_7358_p4);

assign sext_ln70_fu_6639_p1 = $signed(trunc_ln864_218_fu_6629_p4);

assign sext_ln859_126_fu_7642_p1 = $signed(add_ln859_419_fu_7636_p2);

assign sext_ln859_128_fu_7691_p1 = $signed(add_ln859_425_fu_7685_p2);

assign sext_ln859_129_fu_7724_p1 = $signed(add_ln859_429_fu_7718_p2);

assign sext_ln859_222_fu_7525_p1 = $signed(trunc_ln864_236_reg_7924);

assign sext_ln859_223_fu_7547_p1 = $signed(add_ln859_405_fu_7541_p2);

assign sext_ln859_224_fu_7557_p1 = $signed(add_ln859_406_fu_7551_p2);

assign sext_ln859_225_fu_7574_p1 = $signed(add_ln859_409_reg_7939);

assign sext_ln859_226_fu_7583_p1 = $signed(add_ln859_410_fu_7577_p2);

assign sext_ln859_227_fu_7587_p1 = $signed(add_ln859_411_reg_7944);

assign sext_ln859_228_fu_7596_p1 = $signed(add_ln859_412_fu_7590_p2);

assign sext_ln859_229_fu_7606_p1 = $signed(add_ln859_413_fu_7600_p2);

assign sext_ln859_230_fu_7616_p1 = $signed(add_ln859_414_fu_7610_p2);

assign sext_ln859_231_fu_7423_p1 = $signed(add_ln859_417_fu_7417_p2);

assign sext_ln859_232_fu_7633_p1 = $signed(add_ln859_418_reg_7954);

assign sext_ln859_233_fu_7671_p1 = $signed(add_ln859_423_fu_7665_p2);

assign sext_ln859_234_fu_7681_p1 = $signed(add_ln859_424_fu_7675_p2);

assign sext_ln859_235_fu_7704_p1 = $signed(add_ln859_427_fu_7698_p2);

assign sext_ln859_236_fu_7714_p1 = $signed(add_ln859_428_fu_7708_p2);

assign sext_ln859_237_fu_7731_p1 = $signed(add_ln859_432_reg_7974);

assign sext_ln859_238_fu_7740_p1 = $signed(add_ln859_433_fu_7734_p2);

assign sext_ln859_239_fu_7750_p1 = $signed(add_ln859_434_fu_7744_p2);

assign sext_ln859_240_fu_7760_p1 = $signed(add_ln859_435_fu_7754_p2);

assign sext_ln859_241_fu_7773_p1 = $signed(add_ln859_437_fu_7767_p2);

assign sext_ln859_242_fu_7783_p1 = $signed(add_ln859_439_reg_7984);

assign sext_ln859_243_fu_7792_p1 = $signed(add_ln859_440_fu_7786_p2);

assign sext_ln859_244_fu_7802_p1 = $signed(add_ln859_441_fu_7796_p2);

assign sext_ln859_fu_7567_p1 = $signed(add_ln859_407_fu_7561_p2);

assign sext_ln864_89_fu_7488_p1 = $signed(trunc_ln864_220_reg_7873);

assign sext_ln864_90_fu_6787_p1 = $signed(trunc_ln864_221_fu_6777_p4);

assign sext_ln864_91_fu_6914_p1 = $signed(trunc_ln864_223_fu_6904_p4);

assign sext_ln864_92_fu_6980_p1 = $signed(trunc_ln864_225_fu_6970_p4);

assign sext_ln864_93_fu_7506_p1 = $signed(trunc_ln864_228_reg_7899);

assign sext_ln864_94_fu_7515_p1 = $signed(trunc_ln864_233_reg_7914);

assign sext_ln864_fu_6525_p1 = $signed(trunc_ln864_s_fu_6515_p4);

assign shl_ln1319_79_fu_6658_p3 = {{p_read2}, {4'd0}};

assign shl_ln1319_80_fu_6680_p3 = {{p_read2}, {2'd0}};

assign shl_ln1319_81_fu_6874_p3 = {{p_read6}, {6'd0}};

assign shl_ln1319_82_fu_6886_p3 = {{p_read6}, {4'd0}};

assign shl_ln1319_83_fu_7223_p3 = {{p_read12}, {6'd0}};

assign shl_ln1319_84_fu_7235_p3 = {{p_read12}, {3'd0}};

assign shl_ln1319_s_fu_6497_p3 = {{p_read}, {1'd0}};

assign shl_ln2_fu_6529_p3 = {{p_read}, {6'd0}};

assign shl_ln864_83_fu_6593_p3 = {{p_read1}, {3'd0}};

assign shl_ln864_84_fu_6810_p3 = {{p_read4}, {6'd0}};

assign shl_ln864_85_fu_6822_p3 = {{p_read4}, {4'd0}};

assign shl_ln864_86_fu_7034_p3 = {{p_read9}, {5'd0}};

assign shl_ln864_87_fu_7060_p3 = {{p_read9}, {1'd0}};

assign shl_ln864_88_fu_7088_p3 = {{p_read9}, {3'd0}};

assign shl_ln864_89_fu_7146_p3 = {{p_read11}, {5'd0}};

assign shl_ln864_90_fu_7158_p3 = {{p_read11}, {3'd0}};

assign shl_ln864_91_fu_7270_p3 = {{p_read13}, {5'd0}};

assign shl_ln864_92_fu_7322_p3 = {{p_read13}, {3'd0}};

assign shl_ln864_s_fu_6581_p3 = {{p_read1}, {5'd0}};

assign shl_ln_fu_6475_p3 = {{p_read}, {4'd0}};

assign sub_ln1319_108_fu_6670_p2 = (14'd0 - zext_ln1319_177_fu_6666_p1);

assign sub_ln1319_fu_6487_p2 = (14'd0 - zext_ln1319_175_fu_6483_p1);

assign sub_ln864_43_fu_6834_p2 = (zext_ln864_168_fu_6818_p1 - zext_ln864_169_fu_6830_p1);

assign sub_ln864_44_fu_7170_p2 = (zext_ln864_175_fu_7154_p1 - zext_ln864_176_fu_7166_p1);

assign sub_ln864_45_fu_7296_p2 = (zext_ln864_177_fu_7278_p1 - zext_ln70_8_fu_7263_p1);

assign sub_ln864_46_fu_7334_p2 = (zext_ln864_177_fu_7278_p1 - zext_ln864_179_fu_7330_p1);

assign sub_ln864_fu_6605_p2 = (zext_ln864_164_fu_6589_p1 - zext_ln864_165_fu_6601_p1);

assign tmp_fu_6938_p3 = {{p_read7}, {5'd0}};

assign trunc_ln17_108_fu_6730_p4 = {{mul_ln864_78_fu_222_p2[14:5]}};

assign trunc_ln17_109_fu_6744_p4 = {{mul_ln864_79_fu_260_p2[14:5]}};

assign trunc_ln17_110_fu_6758_p4 = {{mul_ln864_80_fu_261_p2[14:5]}};

assign trunc_ln17_111_fu_6796_p4 = {{mul_ln864_81_fu_248_p2[14:5]}};

assign trunc_ln17_112_fu_6840_p4 = {{sub_ln864_43_fu_6834_p2[15:5]}};

assign trunc_ln17_113_fu_6918_p4 = {{mul_ln864_82_fu_257_p2[14:5]}};

assign trunc_ln17_115_fu_7004_p4 = {{mul_ln864_84_fu_225_p2[13:5]}};

assign trunc_ln17_116_fu_7046_p4 = {{mul_ln864_85_fu_268_p2[14:5]}};

assign trunc_ln17_117_fu_7078_p4 = {{add_ln864_46_fu_7072_p2[14:5]}};

assign trunc_ln17_118_fu_7106_p4 = {{add_ln864_47_fu_7100_p2[14:5]}};

assign trunc_ln17_119_fu_7282_p4 = {{mul_ln864_86_fu_237_p2[14:5]}};

assign trunc_ln864_217_fu_6611_p4 = {{sub_ln864_fu_6605_p2[14:5]}};

assign trunc_ln864_218_fu_6629_p4 = {{r_V_183_fu_227_p2[14:5]}};

assign trunc_ln864_219_fu_6698_p4 = {{r_V_184_fu_6692_p2[14:5]}};

assign trunc_ln864_221_fu_6777_p4 = {{r_V_186_fu_238_p2[15:5]}};

assign trunc_ln864_223_fu_6904_p4 = {{r_V_188_fu_6898_p2[15:5]}};

assign trunc_ln864_224_fu_6956_p4 = {{r_V_189_fu_6950_p2[14:5]}};

assign trunc_ln864_225_fu_6970_p4 = {{r_V_190_fu_241_p2[14:5]}};

assign trunc_ln864_229_fu_7176_p4 = {{sub_ln864_44_fu_7170_p2[14:5]}};

assign trunc_ln864_230_fu_7194_p4 = {{r_V_194_fu_276_p2[14:5]}};

assign trunc_ln864_234_fu_7340_p4 = {{sub_ln864_46_fu_7334_p2[14:5]}};

assign trunc_ln864_235_fu_7358_p4 = {{r_V_197_fu_263_p2[14:5]}};

assign trunc_ln864_s_fu_6515_p4 = {{r_V_182_fu_6509_p2[14:5]}};

assign trunc_ln_fu_6461_p4 = {{r_V_fu_259_p2[15:5]}};

assign zext_ln1319_175_fu_6483_p1 = shl_ln_fu_6475_p3;

assign zext_ln1319_176_fu_6505_p1 = shl_ln1319_s_fu_6497_p3;

assign zext_ln1319_177_fu_6666_p1 = shl_ln1319_79_fu_6658_p3;

assign zext_ln1319_178_fu_6688_p1 = shl_ln1319_80_fu_6680_p3;

assign zext_ln1319_179_fu_6712_p1 = p_read3;

assign zext_ln1319_183_fu_6882_p1 = shl_ln1319_81_fu_6874_p3;

assign zext_ln1319_184_fu_6894_p1 = shl_ln1319_82_fu_6886_p3;

assign zext_ln1319_185_fu_6932_p1 = p_read7;

assign zext_ln1319_186_fu_6946_p1 = tmp_fu_6938_p3;

assign zext_ln1319_187_fu_7130_p1 = p_read11;

assign zext_ln1319_189_fu_7231_p1 = shl_ln1319_83_fu_7223_p3;

assign zext_ln1319_190_fu_7243_p1 = shl_ln1319_84_fu_7235_p3;

assign zext_ln17_162_fu_7482_p1 = trunc_ln17_s_reg_7863;

assign zext_ln17_163_fu_6625_p1 = $unsigned(sext_ln17_fu_6621_p1);

assign zext_ln17_164_fu_7485_p1 = trunc_ln17_107_reg_7868;

assign zext_ln17_165_fu_6740_p1 = trunc_ln17_108_fu_6730_p4;

assign zext_ln17_166_fu_6754_p1 = trunc_ln17_109_fu_6744_p4;

assign zext_ln17_167_fu_6768_p1 = trunc_ln17_110_fu_6758_p4;

assign zext_ln17_168_fu_6806_p1 = trunc_ln17_111_fu_6796_p4;

assign zext_ln17_169_fu_6850_p1 = trunc_ln17_112_fu_6840_p4;

assign zext_ln17_170_fu_6928_p1 = trunc_ln17_113_fu_6918_p4;

assign zext_ln17_171_fu_7014_p1 = trunc_ln17_115_fu_7004_p4;

assign zext_ln17_172_fu_7056_p1 = trunc_ln17_116_fu_7046_p4;

assign zext_ln17_173_fu_7116_p1 = trunc_ln17_118_fu_7106_p4;

assign zext_ln17_174_fu_7190_p1 = $unsigned(sext_ln17_43_fu_7186_p1);

assign zext_ln17_175_fu_7292_p1 = trunc_ln17_119_fu_7282_p4;

assign zext_ln17_176_fu_7354_p1 = $unsigned(sext_ln17_44_fu_7350_p1);

assign zext_ln17_fu_7479_p1 = trunc_ln4_reg_7858;

assign zext_ln70_10_fu_7497_p1 = trunc_ln17_114_reg_7884;

assign zext_ln70_8_fu_7263_p1 = p_read13;

assign zext_ln859_100_fu_7537_p1 = add_ln859_404_fu_7531_p2;

assign zext_ln859_102_fu_7620_p1 = add_ln859_415_reg_7949;

assign zext_ln859_103_fu_7571_p1 = add_ln859_408_reg_7934;

assign zext_ln859_104_fu_7646_p1 = add_ln859_420_reg_7959;

assign zext_ln859_105_fu_7629_p1 = add_ln859_416_fu_7623_p2;

assign zext_ln859_106_fu_7695_p1 = add_ln859_426_reg_7964;

assign zext_ln859_107_fu_7451_p1 = add_ln859_430_fu_7445_p2;

assign zext_ln859_108_fu_7655_p1 = add_ln859_421_fu_7649_p2;

assign zext_ln859_109_fu_7728_p1 = add_ln859_431_reg_7969;

assign zext_ln859_110_fu_7764_p1 = add_ln859_436_reg_7979;

assign zext_ln859_fu_7528_p1 = add_ln859_reg_7929;

assign zext_ln864_162_fu_6541_p1 = shl_ln1319_s_fu_6497_p3;

assign zext_ln864_164_fu_6589_p1 = shl_ln864_s_fu_6581_p3;

assign zext_ln864_165_fu_6601_p1 = shl_ln864_83_fu_6593_p3;

assign zext_ln864_168_fu_6818_p1 = shl_ln864_84_fu_6810_p3;

assign zext_ln864_169_fu_6830_p1 = shl_ln864_85_fu_6822_p3;

assign zext_ln864_171_fu_7028_p1 = p_read9;

assign zext_ln864_172_fu_7042_p1 = shl_ln864_86_fu_7034_p3;

assign zext_ln864_173_fu_7068_p1 = shl_ln864_87_fu_7060_p3;

assign zext_ln864_174_fu_7096_p1 = shl_ln864_88_fu_7088_p3;

assign zext_ln864_175_fu_7154_p1 = shl_ln864_89_fu_7146_p3;

assign zext_ln864_176_fu_7166_p1 = shl_ln864_90_fu_7158_p3;

assign zext_ln864_177_fu_7278_p1 = shl_ln864_91_fu_7270_p3;

assign zext_ln864_178_fu_7518_p1 = $unsigned(sext_ln864_94_fu_7515_p1);

assign zext_ln864_179_fu_7330_p1 = shl_ln864_92_fu_7322_p3;

assign zext_ln864_180_fu_7522_p1 = trunc_ln17_120_reg_7919;

assign zext_ln864_fu_6537_p1 = shl_ln2_fu_6529_p3;

endmodule //tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s
