// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config10_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;
output  [8:0] ap_return_7;
output  [8:0] ap_return_8;
output  [8:0] ap_return_9;
output  [8:0] ap_return_10;
output  [8:0] ap_return_11;
output  [8:0] ap_return_12;
output  [8:0] ap_return_13;
output  [8:0] ap_return_14;

wire   [0:0] p_Result_s_fu_236_p3;
wire   [0:0] p_Result_386_fu_216_p1;
wire   [0:0] and_ln420_fu_252_p2;
wire   [8:0] p_Val2_s_fu_226_p4;
wire   [8:0] zext_ln423_fu_258_p1;
wire   [5:0] tmp31_fu_268_p4;
wire   [8:0] p_Val2_139_fu_262_p2;
wire   [0:0] tmp_fu_290_p3;
wire   [0:0] Range1_all_zeros_fu_284_p2;
wire   [0:0] Range1_all_ones_fu_278_p2;
wire   [0:0] p_Result_387_fu_244_p3;
wire   [0:0] select_ln934_fu_298_p3;
wire   [0:0] deleted_zeros_fu_306_p3;
wire   [0:0] icmp_ln1695_fu_220_p2;
wire   [8:0] select_ln348_fu_314_p3;
wire   [0:0] p_Result_346_fu_346_p3;
wire   [0:0] p_Result_388_fu_212_p1;
wire   [0:0] and_ln420_68_fu_362_p2;
wire   [8:0] p_Val2_140_fu_336_p4;
wire   [8:0] zext_ln423_68_fu_368_p1;
wire   [5:0] tmp_36_fu_378_p4;
wire   [8:0] p_Val2_141_fu_372_p2;
wire   [0:0] tmp_213_fu_400_p3;
wire   [0:0] Range1_all_zeros_68_fu_394_p2;
wire   [0:0] Range1_all_ones_68_fu_388_p2;
wire   [0:0] p_Result_389_fu_354_p3;
wire   [0:0] select_ln934_68_fu_408_p3;
wire   [0:0] deleted_zeros_68_fu_416_p3;
wire   [0:0] icmp_ln1695_68_fu_330_p2;
wire   [8:0] select_ln348_68_fu_424_p3;
wire   [0:0] p_Result_349_fu_456_p3;
wire   [0:0] p_Result_390_fu_208_p1;
wire   [0:0] and_ln420_69_fu_472_p2;
wire   [8:0] p_Val2_142_fu_446_p4;
wire   [8:0] zext_ln423_69_fu_478_p1;
wire   [5:0] tmp_s_fu_488_p4;
wire   [8:0] p_Val2_143_fu_482_p2;
wire   [0:0] tmp_216_fu_510_p3;
wire   [0:0] Range1_all_zeros_69_fu_504_p2;
wire   [0:0] Range1_all_ones_69_fu_498_p2;
wire   [0:0] p_Result_391_fu_464_p3;
wire   [0:0] select_ln934_69_fu_518_p3;
wire   [0:0] deleted_zeros_69_fu_526_p3;
wire   [0:0] icmp_ln1695_69_fu_440_p2;
wire   [8:0] select_ln348_69_fu_534_p3;
wire   [0:0] p_Result_352_fu_566_p3;
wire   [0:0] p_Result_392_fu_204_p1;
wire   [0:0] and_ln420_70_fu_582_p2;
wire   [8:0] p_Val2_144_fu_556_p4;
wire   [8:0] zext_ln423_70_fu_588_p1;
wire   [5:0] tmp_73_fu_598_p4;
wire   [8:0] p_Val2_145_fu_592_p2;
wire   [0:0] tmp_219_fu_620_p3;
wire   [0:0] Range1_all_zeros_70_fu_614_p2;
wire   [0:0] Range1_all_ones_70_fu_608_p2;
wire   [0:0] p_Result_393_fu_574_p3;
wire   [0:0] select_ln934_70_fu_628_p3;
wire   [0:0] deleted_zeros_70_fu_636_p3;
wire   [0:0] icmp_ln1695_70_fu_550_p2;
wire   [8:0] select_ln348_70_fu_644_p3;
wire   [0:0] p_Result_355_fu_676_p3;
wire   [0:0] p_Result_394_fu_200_p1;
wire   [0:0] and_ln420_71_fu_692_p2;
wire   [8:0] p_Val2_146_fu_666_p4;
wire   [8:0] zext_ln423_71_fu_698_p1;
wire   [5:0] tmp_74_fu_708_p4;
wire   [8:0] p_Val2_147_fu_702_p2;
wire   [0:0] tmp_222_fu_730_p3;
wire   [0:0] Range1_all_zeros_71_fu_724_p2;
wire   [0:0] Range1_all_ones_71_fu_718_p2;
wire   [0:0] p_Result_395_fu_684_p3;
wire   [0:0] select_ln934_71_fu_738_p3;
wire   [0:0] deleted_zeros_71_fu_746_p3;
wire   [0:0] icmp_ln1695_71_fu_660_p2;
wire   [8:0] select_ln348_71_fu_754_p3;
wire   [0:0] p_Result_358_fu_786_p3;
wire   [0:0] p_Result_396_fu_196_p1;
wire   [0:0] and_ln420_72_fu_802_p2;
wire   [8:0] p_Val2_148_fu_776_p4;
wire   [8:0] zext_ln423_72_fu_808_p1;
wire   [5:0] tmp_75_fu_818_p4;
wire   [8:0] p_Val2_149_fu_812_p2;
wire   [0:0] tmp_225_fu_840_p3;
wire   [0:0] Range1_all_zeros_72_fu_834_p2;
wire   [0:0] Range1_all_ones_72_fu_828_p2;
wire   [0:0] p_Result_397_fu_794_p3;
wire   [0:0] select_ln934_72_fu_848_p3;
wire   [0:0] deleted_zeros_72_fu_856_p3;
wire   [0:0] icmp_ln1695_72_fu_770_p2;
wire   [8:0] select_ln348_72_fu_864_p3;
wire   [0:0] p_Result_361_fu_896_p3;
wire   [0:0] p_Result_398_fu_192_p1;
wire   [0:0] and_ln420_73_fu_912_p2;
wire   [8:0] p_Val2_150_fu_886_p4;
wire   [8:0] zext_ln423_73_fu_918_p1;
wire   [5:0] tmp_76_fu_928_p4;
wire   [8:0] p_Val2_151_fu_922_p2;
wire   [0:0] tmp_228_fu_950_p3;
wire   [0:0] Range1_all_zeros_73_fu_944_p2;
wire   [0:0] Range1_all_ones_73_fu_938_p2;
wire   [0:0] p_Result_399_fu_904_p3;
wire   [0:0] select_ln934_73_fu_958_p3;
wire   [0:0] deleted_zeros_73_fu_966_p3;
wire   [0:0] icmp_ln1695_73_fu_880_p2;
wire   [8:0] select_ln348_73_fu_974_p3;
wire   [0:0] p_Result_364_fu_1006_p3;
wire   [0:0] p_Result_400_fu_188_p1;
wire   [0:0] and_ln420_74_fu_1022_p2;
wire   [8:0] p_Val2_152_fu_996_p4;
wire   [8:0] zext_ln423_74_fu_1028_p1;
wire   [5:0] tmp_77_fu_1038_p4;
wire   [8:0] p_Val2_153_fu_1032_p2;
wire   [0:0] tmp_231_fu_1060_p3;
wire   [0:0] Range1_all_zeros_74_fu_1054_p2;
wire   [0:0] Range1_all_ones_74_fu_1048_p2;
wire   [0:0] p_Result_401_fu_1014_p3;
wire   [0:0] select_ln934_74_fu_1068_p3;
wire   [0:0] deleted_zeros_74_fu_1076_p3;
wire   [0:0] icmp_ln1695_74_fu_990_p2;
wire   [8:0] select_ln348_74_fu_1084_p3;
wire   [0:0] p_Result_367_fu_1116_p3;
wire   [0:0] p_Result_402_fu_184_p1;
wire   [0:0] and_ln420_75_fu_1132_p2;
wire   [8:0] p_Val2_154_fu_1106_p4;
wire   [8:0] zext_ln423_75_fu_1138_p1;
wire   [5:0] tmp_78_fu_1148_p4;
wire   [8:0] p_Val2_155_fu_1142_p2;
wire   [0:0] tmp_234_fu_1170_p3;
wire   [0:0] Range1_all_zeros_75_fu_1164_p2;
wire   [0:0] Range1_all_ones_75_fu_1158_p2;
wire   [0:0] p_Result_403_fu_1124_p3;
wire   [0:0] select_ln934_75_fu_1178_p3;
wire   [0:0] deleted_zeros_75_fu_1186_p3;
wire   [0:0] icmp_ln1695_75_fu_1100_p2;
wire   [8:0] select_ln348_75_fu_1194_p3;
wire   [0:0] p_Result_370_fu_1226_p3;
wire   [0:0] p_Result_404_fu_180_p1;
wire   [0:0] and_ln420_76_fu_1242_p2;
wire   [8:0] p_Val2_156_fu_1216_p4;
wire   [8:0] zext_ln423_76_fu_1248_p1;
wire   [5:0] tmp_79_fu_1258_p4;
wire   [8:0] p_Val2_157_fu_1252_p2;
wire   [0:0] tmp_237_fu_1280_p3;
wire   [0:0] Range1_all_zeros_76_fu_1274_p2;
wire   [0:0] Range1_all_ones_76_fu_1268_p2;
wire   [0:0] p_Result_405_fu_1234_p3;
wire   [0:0] select_ln934_76_fu_1288_p3;
wire   [0:0] deleted_zeros_76_fu_1296_p3;
wire   [0:0] icmp_ln1695_76_fu_1210_p2;
wire   [8:0] select_ln348_76_fu_1304_p3;
wire   [0:0] p_Result_373_fu_1336_p3;
wire   [0:0] p_Result_406_fu_176_p1;
wire   [0:0] and_ln420_77_fu_1352_p2;
wire   [8:0] p_Val2_158_fu_1326_p4;
wire   [8:0] zext_ln423_77_fu_1358_p1;
wire   [5:0] tmp_80_fu_1368_p4;
wire   [8:0] p_Val2_159_fu_1362_p2;
wire   [0:0] tmp_240_fu_1390_p3;
wire   [0:0] Range1_all_zeros_77_fu_1384_p2;
wire   [0:0] Range1_all_ones_77_fu_1378_p2;
wire   [0:0] p_Result_407_fu_1344_p3;
wire   [0:0] select_ln934_77_fu_1398_p3;
wire   [0:0] deleted_zeros_77_fu_1406_p3;
wire   [0:0] icmp_ln1695_77_fu_1320_p2;
wire   [8:0] select_ln348_77_fu_1414_p3;
wire   [0:0] p_Result_376_fu_1446_p3;
wire   [0:0] p_Result_408_fu_172_p1;
wire   [0:0] and_ln420_78_fu_1462_p2;
wire   [8:0] p_Val2_160_fu_1436_p4;
wire   [8:0] zext_ln423_78_fu_1468_p1;
wire   [5:0] tmp_81_fu_1478_p4;
wire   [8:0] p_Val2_161_fu_1472_p2;
wire   [0:0] tmp_243_fu_1500_p3;
wire   [0:0] Range1_all_zeros_78_fu_1494_p2;
wire   [0:0] Range1_all_ones_78_fu_1488_p2;
wire   [0:0] p_Result_409_fu_1454_p3;
wire   [0:0] select_ln934_78_fu_1508_p3;
wire   [0:0] deleted_zeros_78_fu_1516_p3;
wire   [0:0] icmp_ln1695_78_fu_1430_p2;
wire   [8:0] select_ln348_78_fu_1524_p3;
wire   [0:0] p_Result_379_fu_1556_p3;
wire   [0:0] p_Result_410_fu_168_p1;
wire   [0:0] and_ln420_79_fu_1572_p2;
wire   [8:0] p_Val2_162_fu_1546_p4;
wire   [8:0] zext_ln423_79_fu_1578_p1;
wire   [5:0] tmp_82_fu_1588_p4;
wire   [8:0] p_Val2_163_fu_1582_p2;
wire   [0:0] tmp_246_fu_1610_p3;
wire   [0:0] Range1_all_zeros_79_fu_1604_p2;
wire   [0:0] Range1_all_ones_79_fu_1598_p2;
wire   [0:0] p_Result_411_fu_1564_p3;
wire   [0:0] select_ln934_79_fu_1618_p3;
wire   [0:0] deleted_zeros_79_fu_1626_p3;
wire   [0:0] icmp_ln1695_79_fu_1540_p2;
wire   [8:0] select_ln348_79_fu_1634_p3;
wire   [0:0] p_Result_382_fu_1666_p3;
wire   [0:0] p_Result_412_fu_164_p1;
wire   [0:0] and_ln420_80_fu_1682_p2;
wire   [8:0] p_Val2_164_fu_1656_p4;
wire   [8:0] zext_ln423_80_fu_1688_p1;
wire   [5:0] tmp_83_fu_1698_p4;
wire   [8:0] p_Val2_165_fu_1692_p2;
wire   [0:0] tmp_249_fu_1720_p3;
wire   [0:0] Range1_all_zeros_80_fu_1714_p2;
wire   [0:0] Range1_all_ones_80_fu_1708_p2;
wire   [0:0] p_Result_413_fu_1674_p3;
wire   [0:0] select_ln934_80_fu_1728_p3;
wire   [0:0] deleted_zeros_80_fu_1736_p3;
wire   [0:0] icmp_ln1695_80_fu_1650_p2;
wire   [8:0] select_ln348_80_fu_1744_p3;
wire   [0:0] p_Result_385_fu_1776_p3;
wire   [0:0] p_Result_414_fu_160_p1;
wire   [0:0] and_ln420_81_fu_1792_p2;
wire   [8:0] p_Val2_166_fu_1766_p4;
wire   [8:0] zext_ln423_81_fu_1798_p1;
wire   [5:0] tmp_84_fu_1808_p4;
wire   [8:0] p_Val2_167_fu_1802_p2;
wire   [0:0] tmp_252_fu_1830_p3;
wire   [0:0] Range1_all_zeros_81_fu_1824_p2;
wire   [0:0] Range1_all_ones_81_fu_1818_p2;
wire   [0:0] p_Result_415_fu_1784_p3;
wire   [0:0] select_ln934_81_fu_1838_p3;
wire   [0:0] deleted_zeros_81_fu_1846_p3;
wire   [0:0] icmp_ln1695_81_fu_1760_p2;
wire   [8:0] select_ln348_81_fu_1854_p3;
wire   [8:0] select_ln1695_fu_322_p3;
wire   [8:0] select_ln1695_68_fu_432_p3;
wire   [8:0] select_ln1695_69_fu_542_p3;
wire   [8:0] select_ln1695_70_fu_652_p3;
wire   [8:0] select_ln1695_71_fu_762_p3;
wire   [8:0] select_ln1695_72_fu_872_p3;
wire   [8:0] select_ln1695_73_fu_982_p3;
wire   [8:0] select_ln1695_74_fu_1092_p3;
wire   [8:0] select_ln1695_75_fu_1202_p3;
wire   [8:0] select_ln1695_76_fu_1312_p3;
wire   [8:0] select_ln1695_77_fu_1422_p3;
wire   [8:0] select_ln1695_78_fu_1532_p3;
wire   [8:0] select_ln1695_79_fu_1642_p3;
wire   [8:0] select_ln1695_80_fu_1752_p3;
wire   [8:0] select_ln1695_81_fu_1862_p3;
wire    ap_ce_reg;

assign Range1_all_ones_68_fu_388_p2 = ((tmp_36_fu_378_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_69_fu_498_p2 = ((tmp_s_fu_488_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_70_fu_608_p2 = ((tmp_73_fu_598_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_71_fu_718_p2 = ((tmp_74_fu_708_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_72_fu_828_p2 = ((tmp_75_fu_818_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_73_fu_938_p2 = ((tmp_76_fu_928_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_74_fu_1048_p2 = ((tmp_77_fu_1038_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_75_fu_1158_p2 = ((tmp_78_fu_1148_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_76_fu_1268_p2 = ((tmp_79_fu_1258_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_77_fu_1378_p2 = ((tmp_80_fu_1368_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_78_fu_1488_p2 = ((tmp_81_fu_1478_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_79_fu_1598_p2 = ((tmp_82_fu_1588_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_80_fu_1708_p2 = ((tmp_83_fu_1698_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_81_fu_1818_p2 = ((tmp_84_fu_1808_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_278_p2 = ((tmp31_fu_268_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_68_fu_394_p2 = ((tmp_36_fu_378_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_69_fu_504_p2 = ((tmp_s_fu_488_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_70_fu_614_p2 = ((tmp_73_fu_598_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_71_fu_724_p2 = ((tmp_74_fu_708_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_72_fu_834_p2 = ((tmp_75_fu_818_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_73_fu_944_p2 = ((tmp_76_fu_928_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_74_fu_1054_p2 = ((tmp_77_fu_1038_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_75_fu_1164_p2 = ((tmp_78_fu_1148_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_76_fu_1274_p2 = ((tmp_79_fu_1258_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_77_fu_1384_p2 = ((tmp_80_fu_1368_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_78_fu_1494_p2 = ((tmp_81_fu_1478_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_79_fu_1604_p2 = ((tmp_82_fu_1588_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_80_fu_1714_p2 = ((tmp_83_fu_1698_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_81_fu_1824_p2 = ((tmp_84_fu_1808_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_284_p2 = ((tmp31_fu_268_p4 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln420_68_fu_362_p2 = (p_Result_388_fu_212_p1 & p_Result_346_fu_346_p3);

assign and_ln420_69_fu_472_p2 = (p_Result_390_fu_208_p1 & p_Result_349_fu_456_p3);

assign and_ln420_70_fu_582_p2 = (p_Result_392_fu_204_p1 & p_Result_352_fu_566_p3);

assign and_ln420_71_fu_692_p2 = (p_Result_394_fu_200_p1 & p_Result_355_fu_676_p3);

assign and_ln420_72_fu_802_p2 = (p_Result_396_fu_196_p1 & p_Result_358_fu_786_p3);

assign and_ln420_73_fu_912_p2 = (p_Result_398_fu_192_p1 & p_Result_361_fu_896_p3);

assign and_ln420_74_fu_1022_p2 = (p_Result_400_fu_188_p1 & p_Result_364_fu_1006_p3);

assign and_ln420_75_fu_1132_p2 = (p_Result_402_fu_184_p1 & p_Result_367_fu_1116_p3);

assign and_ln420_76_fu_1242_p2 = (p_Result_404_fu_180_p1 & p_Result_370_fu_1226_p3);

assign and_ln420_77_fu_1352_p2 = (p_Result_406_fu_176_p1 & p_Result_373_fu_1336_p3);

assign and_ln420_78_fu_1462_p2 = (p_Result_408_fu_172_p1 & p_Result_376_fu_1446_p3);

assign and_ln420_79_fu_1572_p2 = (p_Result_410_fu_168_p1 & p_Result_379_fu_1556_p3);

assign and_ln420_80_fu_1682_p2 = (p_Result_412_fu_164_p1 & p_Result_382_fu_1666_p3);

assign and_ln420_81_fu_1792_p2 = (p_Result_414_fu_160_p1 & p_Result_385_fu_1776_p3);

assign and_ln420_fu_252_p2 = (p_Result_s_fu_236_p3 & p_Result_386_fu_216_p1);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1695_fu_322_p3;

assign ap_return_1 = select_ln1695_68_fu_432_p3;

assign ap_return_10 = select_ln1695_77_fu_1422_p3;

assign ap_return_11 = select_ln1695_78_fu_1532_p3;

assign ap_return_12 = select_ln1695_79_fu_1642_p3;

assign ap_return_13 = select_ln1695_80_fu_1752_p3;

assign ap_return_14 = select_ln1695_81_fu_1862_p3;

assign ap_return_2 = select_ln1695_69_fu_542_p3;

assign ap_return_3 = select_ln1695_70_fu_652_p3;

assign ap_return_4 = select_ln1695_71_fu_762_p3;

assign ap_return_5 = select_ln1695_72_fu_872_p3;

assign ap_return_6 = select_ln1695_73_fu_982_p3;

assign ap_return_7 = select_ln1695_74_fu_1092_p3;

assign ap_return_8 = select_ln1695_75_fu_1202_p3;

assign ap_return_9 = select_ln1695_76_fu_1312_p3;

assign deleted_zeros_68_fu_416_p3 = ((p_Result_389_fu_354_p3[0:0] == 1'b1) ? select_ln934_68_fu_408_p3 : Range1_all_zeros_68_fu_394_p2);

assign deleted_zeros_69_fu_526_p3 = ((p_Result_391_fu_464_p3[0:0] == 1'b1) ? select_ln934_69_fu_518_p3 : Range1_all_zeros_69_fu_504_p2);

assign deleted_zeros_70_fu_636_p3 = ((p_Result_393_fu_574_p3[0:0] == 1'b1) ? select_ln934_70_fu_628_p3 : Range1_all_zeros_70_fu_614_p2);

assign deleted_zeros_71_fu_746_p3 = ((p_Result_395_fu_684_p3[0:0] == 1'b1) ? select_ln934_71_fu_738_p3 : Range1_all_zeros_71_fu_724_p2);

assign deleted_zeros_72_fu_856_p3 = ((p_Result_397_fu_794_p3[0:0] == 1'b1) ? select_ln934_72_fu_848_p3 : Range1_all_zeros_72_fu_834_p2);

assign deleted_zeros_73_fu_966_p3 = ((p_Result_399_fu_904_p3[0:0] == 1'b1) ? select_ln934_73_fu_958_p3 : Range1_all_zeros_73_fu_944_p2);

assign deleted_zeros_74_fu_1076_p3 = ((p_Result_401_fu_1014_p3[0:0] == 1'b1) ? select_ln934_74_fu_1068_p3 : Range1_all_zeros_74_fu_1054_p2);

assign deleted_zeros_75_fu_1186_p3 = ((p_Result_403_fu_1124_p3[0:0] == 1'b1) ? select_ln934_75_fu_1178_p3 : Range1_all_zeros_75_fu_1164_p2);

assign deleted_zeros_76_fu_1296_p3 = ((p_Result_405_fu_1234_p3[0:0] == 1'b1) ? select_ln934_76_fu_1288_p3 : Range1_all_zeros_76_fu_1274_p2);

assign deleted_zeros_77_fu_1406_p3 = ((p_Result_407_fu_1344_p3[0:0] == 1'b1) ? select_ln934_77_fu_1398_p3 : Range1_all_zeros_77_fu_1384_p2);

assign deleted_zeros_78_fu_1516_p3 = ((p_Result_409_fu_1454_p3[0:0] == 1'b1) ? select_ln934_78_fu_1508_p3 : Range1_all_zeros_78_fu_1494_p2);

assign deleted_zeros_79_fu_1626_p3 = ((p_Result_411_fu_1564_p3[0:0] == 1'b1) ? select_ln934_79_fu_1618_p3 : Range1_all_zeros_79_fu_1604_p2);

assign deleted_zeros_80_fu_1736_p3 = ((p_Result_413_fu_1674_p3[0:0] == 1'b1) ? select_ln934_80_fu_1728_p3 : Range1_all_zeros_80_fu_1714_p2);

assign deleted_zeros_81_fu_1846_p3 = ((p_Result_415_fu_1784_p3[0:0] == 1'b1) ? select_ln934_81_fu_1838_p3 : Range1_all_zeros_81_fu_1824_p2);

assign deleted_zeros_fu_306_p3 = ((p_Result_387_fu_244_p3[0:0] == 1'b1) ? select_ln934_fu_298_p3 : Range1_all_zeros_fu_284_p2);

assign icmp_ln1695_68_fu_330_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_69_fu_440_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_70_fu_550_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_71_fu_660_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_72_fu_770_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_73_fu_880_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_74_fu_990_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_75_fu_1100_p2 = (($signed(p_read8) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_76_fu_1210_p2 = (($signed(p_read9) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_77_fu_1320_p2 = (($signed(p_read10) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_78_fu_1430_p2 = (($signed(p_read11) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_79_fu_1540_p2 = (($signed(p_read12) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_80_fu_1650_p2 = (($signed(p_read13) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_81_fu_1760_p2 = (($signed(p_read14) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_fu_220_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign p_Result_346_fu_346_p3 = p_read1[32'd1];

assign p_Result_349_fu_456_p3 = p_read2[32'd1];

assign p_Result_352_fu_566_p3 = p_read3[32'd1];

assign p_Result_355_fu_676_p3 = p_read4[32'd1];

assign p_Result_358_fu_786_p3 = p_read5[32'd1];

assign p_Result_361_fu_896_p3 = p_read6[32'd1];

assign p_Result_364_fu_1006_p3 = p_read7[32'd1];

assign p_Result_367_fu_1116_p3 = p_read8[32'd1];

assign p_Result_370_fu_1226_p3 = p_read9[32'd1];

assign p_Result_373_fu_1336_p3 = p_read10[32'd1];

assign p_Result_376_fu_1446_p3 = p_read11[32'd1];

assign p_Result_379_fu_1556_p3 = p_read12[32'd1];

assign p_Result_382_fu_1666_p3 = p_read13[32'd1];

assign p_Result_385_fu_1776_p3 = p_read14[32'd1];

assign p_Result_386_fu_216_p1 = p_read[0:0];

assign p_Result_387_fu_244_p3 = p_read[32'd9];

assign p_Result_388_fu_212_p1 = p_read1[0:0];

assign p_Result_389_fu_354_p3 = p_read1[32'd9];

assign p_Result_390_fu_208_p1 = p_read2[0:0];

assign p_Result_391_fu_464_p3 = p_read2[32'd9];

assign p_Result_392_fu_204_p1 = p_read3[0:0];

assign p_Result_393_fu_574_p3 = p_read3[32'd9];

assign p_Result_394_fu_200_p1 = p_read4[0:0];

assign p_Result_395_fu_684_p3 = p_read4[32'd9];

assign p_Result_396_fu_196_p1 = p_read5[0:0];

assign p_Result_397_fu_794_p3 = p_read5[32'd9];

assign p_Result_398_fu_192_p1 = p_read6[0:0];

assign p_Result_399_fu_904_p3 = p_read6[32'd9];

assign p_Result_400_fu_188_p1 = p_read7[0:0];

assign p_Result_401_fu_1014_p3 = p_read7[32'd9];

assign p_Result_402_fu_184_p1 = p_read8[0:0];

assign p_Result_403_fu_1124_p3 = p_read8[32'd9];

assign p_Result_404_fu_180_p1 = p_read9[0:0];

assign p_Result_405_fu_1234_p3 = p_read9[32'd9];

assign p_Result_406_fu_176_p1 = p_read10[0:0];

assign p_Result_407_fu_1344_p3 = p_read10[32'd9];

assign p_Result_408_fu_172_p1 = p_read11[0:0];

assign p_Result_409_fu_1454_p3 = p_read11[32'd9];

assign p_Result_410_fu_168_p1 = p_read12[0:0];

assign p_Result_411_fu_1564_p3 = p_read12[32'd9];

assign p_Result_412_fu_164_p1 = p_read13[0:0];

assign p_Result_413_fu_1674_p3 = p_read13[32'd9];

assign p_Result_414_fu_160_p1 = p_read14[0:0];

assign p_Result_415_fu_1784_p3 = p_read14[32'd9];

assign p_Result_s_fu_236_p3 = p_read[32'd1];

assign p_Val2_139_fu_262_p2 = (p_Val2_s_fu_226_p4 + zext_ln423_fu_258_p1);

assign p_Val2_140_fu_336_p4 = {{p_read1[9:1]}};

assign p_Val2_141_fu_372_p2 = (p_Val2_140_fu_336_p4 + zext_ln423_68_fu_368_p1);

assign p_Val2_142_fu_446_p4 = {{p_read2[9:1]}};

assign p_Val2_143_fu_482_p2 = (p_Val2_142_fu_446_p4 + zext_ln423_69_fu_478_p1);

assign p_Val2_144_fu_556_p4 = {{p_read3[9:1]}};

assign p_Val2_145_fu_592_p2 = (p_Val2_144_fu_556_p4 + zext_ln423_70_fu_588_p1);

assign p_Val2_146_fu_666_p4 = {{p_read4[9:1]}};

assign p_Val2_147_fu_702_p2 = (p_Val2_146_fu_666_p4 + zext_ln423_71_fu_698_p1);

assign p_Val2_148_fu_776_p4 = {{p_read5[9:1]}};

assign p_Val2_149_fu_812_p2 = (p_Val2_148_fu_776_p4 + zext_ln423_72_fu_808_p1);

assign p_Val2_150_fu_886_p4 = {{p_read6[9:1]}};

assign p_Val2_151_fu_922_p2 = (p_Val2_150_fu_886_p4 + zext_ln423_73_fu_918_p1);

assign p_Val2_152_fu_996_p4 = {{p_read7[9:1]}};

assign p_Val2_153_fu_1032_p2 = (p_Val2_152_fu_996_p4 + zext_ln423_74_fu_1028_p1);

assign p_Val2_154_fu_1106_p4 = {{p_read8[9:1]}};

assign p_Val2_155_fu_1142_p2 = (p_Val2_154_fu_1106_p4 + zext_ln423_75_fu_1138_p1);

assign p_Val2_156_fu_1216_p4 = {{p_read9[9:1]}};

assign p_Val2_157_fu_1252_p2 = (p_Val2_156_fu_1216_p4 + zext_ln423_76_fu_1248_p1);

assign p_Val2_158_fu_1326_p4 = {{p_read10[9:1]}};

assign p_Val2_159_fu_1362_p2 = (p_Val2_158_fu_1326_p4 + zext_ln423_77_fu_1358_p1);

assign p_Val2_160_fu_1436_p4 = {{p_read11[9:1]}};

assign p_Val2_161_fu_1472_p2 = (p_Val2_160_fu_1436_p4 + zext_ln423_78_fu_1468_p1);

assign p_Val2_162_fu_1546_p4 = {{p_read12[9:1]}};

assign p_Val2_163_fu_1582_p2 = (p_Val2_162_fu_1546_p4 + zext_ln423_79_fu_1578_p1);

assign p_Val2_164_fu_1656_p4 = {{p_read13[9:1]}};

assign p_Val2_165_fu_1692_p2 = (p_Val2_164_fu_1656_p4 + zext_ln423_80_fu_1688_p1);

assign p_Val2_166_fu_1766_p4 = {{p_read14[9:1]}};

assign p_Val2_167_fu_1802_p2 = (p_Val2_166_fu_1766_p4 + zext_ln423_81_fu_1798_p1);

assign p_Val2_s_fu_226_p4 = {{p_read[9:1]}};

assign select_ln1695_68_fu_432_p3 = ((icmp_ln1695_68_fu_330_p2[0:0] == 1'b1) ? select_ln348_68_fu_424_p3 : 9'd0);

assign select_ln1695_69_fu_542_p3 = ((icmp_ln1695_69_fu_440_p2[0:0] == 1'b1) ? select_ln348_69_fu_534_p3 : 9'd0);

assign select_ln1695_70_fu_652_p3 = ((icmp_ln1695_70_fu_550_p2[0:0] == 1'b1) ? select_ln348_70_fu_644_p3 : 9'd0);

assign select_ln1695_71_fu_762_p3 = ((icmp_ln1695_71_fu_660_p2[0:0] == 1'b1) ? select_ln348_71_fu_754_p3 : 9'd0);

assign select_ln1695_72_fu_872_p3 = ((icmp_ln1695_72_fu_770_p2[0:0] == 1'b1) ? select_ln348_72_fu_864_p3 : 9'd0);

assign select_ln1695_73_fu_982_p3 = ((icmp_ln1695_73_fu_880_p2[0:0] == 1'b1) ? select_ln348_73_fu_974_p3 : 9'd0);

assign select_ln1695_74_fu_1092_p3 = ((icmp_ln1695_74_fu_990_p2[0:0] == 1'b1) ? select_ln348_74_fu_1084_p3 : 9'd0);

assign select_ln1695_75_fu_1202_p3 = ((icmp_ln1695_75_fu_1100_p2[0:0] == 1'b1) ? select_ln348_75_fu_1194_p3 : 9'd0);

assign select_ln1695_76_fu_1312_p3 = ((icmp_ln1695_76_fu_1210_p2[0:0] == 1'b1) ? select_ln348_76_fu_1304_p3 : 9'd0);

assign select_ln1695_77_fu_1422_p3 = ((icmp_ln1695_77_fu_1320_p2[0:0] == 1'b1) ? select_ln348_77_fu_1414_p3 : 9'd0);

assign select_ln1695_78_fu_1532_p3 = ((icmp_ln1695_78_fu_1430_p2[0:0] == 1'b1) ? select_ln348_78_fu_1524_p3 : 9'd0);

assign select_ln1695_79_fu_1642_p3 = ((icmp_ln1695_79_fu_1540_p2[0:0] == 1'b1) ? select_ln348_79_fu_1634_p3 : 9'd0);

assign select_ln1695_80_fu_1752_p3 = ((icmp_ln1695_80_fu_1650_p2[0:0] == 1'b1) ? select_ln348_80_fu_1744_p3 : 9'd0);

assign select_ln1695_81_fu_1862_p3 = ((icmp_ln1695_81_fu_1760_p2[0:0] == 1'b1) ? select_ln348_81_fu_1854_p3 : 9'd0);

assign select_ln1695_fu_322_p3 = ((icmp_ln1695_fu_220_p2[0:0] == 1'b1) ? select_ln348_fu_314_p3 : 9'd0);

assign select_ln348_68_fu_424_p3 = ((deleted_zeros_68_fu_416_p3[0:0] == 1'b1) ? p_Val2_141_fu_372_p2 : 9'd511);

assign select_ln348_69_fu_534_p3 = ((deleted_zeros_69_fu_526_p3[0:0] == 1'b1) ? p_Val2_143_fu_482_p2 : 9'd511);

assign select_ln348_70_fu_644_p3 = ((deleted_zeros_70_fu_636_p3[0:0] == 1'b1) ? p_Val2_145_fu_592_p2 : 9'd511);

assign select_ln348_71_fu_754_p3 = ((deleted_zeros_71_fu_746_p3[0:0] == 1'b1) ? p_Val2_147_fu_702_p2 : 9'd511);

assign select_ln348_72_fu_864_p3 = ((deleted_zeros_72_fu_856_p3[0:0] == 1'b1) ? p_Val2_149_fu_812_p2 : 9'd511);

assign select_ln348_73_fu_974_p3 = ((deleted_zeros_73_fu_966_p3[0:0] == 1'b1) ? p_Val2_151_fu_922_p2 : 9'd511);

assign select_ln348_74_fu_1084_p3 = ((deleted_zeros_74_fu_1076_p3[0:0] == 1'b1) ? p_Val2_153_fu_1032_p2 : 9'd511);

assign select_ln348_75_fu_1194_p3 = ((deleted_zeros_75_fu_1186_p3[0:0] == 1'b1) ? p_Val2_155_fu_1142_p2 : 9'd511);

assign select_ln348_76_fu_1304_p3 = ((deleted_zeros_76_fu_1296_p3[0:0] == 1'b1) ? p_Val2_157_fu_1252_p2 : 9'd511);

assign select_ln348_77_fu_1414_p3 = ((deleted_zeros_77_fu_1406_p3[0:0] == 1'b1) ? p_Val2_159_fu_1362_p2 : 9'd511);

assign select_ln348_78_fu_1524_p3 = ((deleted_zeros_78_fu_1516_p3[0:0] == 1'b1) ? p_Val2_161_fu_1472_p2 : 9'd511);

assign select_ln348_79_fu_1634_p3 = ((deleted_zeros_79_fu_1626_p3[0:0] == 1'b1) ? p_Val2_163_fu_1582_p2 : 9'd511);

assign select_ln348_80_fu_1744_p3 = ((deleted_zeros_80_fu_1736_p3[0:0] == 1'b1) ? p_Val2_165_fu_1692_p2 : 9'd511);

assign select_ln348_81_fu_1854_p3 = ((deleted_zeros_81_fu_1846_p3[0:0] == 1'b1) ? p_Val2_167_fu_1802_p2 : 9'd511);

assign select_ln348_fu_314_p3 = ((deleted_zeros_fu_306_p3[0:0] == 1'b1) ? p_Val2_139_fu_262_p2 : 9'd511);

assign select_ln934_68_fu_408_p3 = ((tmp_213_fu_400_p3[0:0] == 1'b1) ? Range1_all_zeros_68_fu_394_p2 : Range1_all_ones_68_fu_388_p2);

assign select_ln934_69_fu_518_p3 = ((tmp_216_fu_510_p3[0:0] == 1'b1) ? Range1_all_zeros_69_fu_504_p2 : Range1_all_ones_69_fu_498_p2);

assign select_ln934_70_fu_628_p3 = ((tmp_219_fu_620_p3[0:0] == 1'b1) ? Range1_all_zeros_70_fu_614_p2 : Range1_all_ones_70_fu_608_p2);

assign select_ln934_71_fu_738_p3 = ((tmp_222_fu_730_p3[0:0] == 1'b1) ? Range1_all_zeros_71_fu_724_p2 : Range1_all_ones_71_fu_718_p2);

assign select_ln934_72_fu_848_p3 = ((tmp_225_fu_840_p3[0:0] == 1'b1) ? Range1_all_zeros_72_fu_834_p2 : Range1_all_ones_72_fu_828_p2);

assign select_ln934_73_fu_958_p3 = ((tmp_228_fu_950_p3[0:0] == 1'b1) ? Range1_all_zeros_73_fu_944_p2 : Range1_all_ones_73_fu_938_p2);

assign select_ln934_74_fu_1068_p3 = ((tmp_231_fu_1060_p3[0:0] == 1'b1) ? Range1_all_zeros_74_fu_1054_p2 : Range1_all_ones_74_fu_1048_p2);

assign select_ln934_75_fu_1178_p3 = ((tmp_234_fu_1170_p3[0:0] == 1'b1) ? Range1_all_zeros_75_fu_1164_p2 : Range1_all_ones_75_fu_1158_p2);

assign select_ln934_76_fu_1288_p3 = ((tmp_237_fu_1280_p3[0:0] == 1'b1) ? Range1_all_zeros_76_fu_1274_p2 : Range1_all_ones_76_fu_1268_p2);

assign select_ln934_77_fu_1398_p3 = ((tmp_240_fu_1390_p3[0:0] == 1'b1) ? Range1_all_zeros_77_fu_1384_p2 : Range1_all_ones_77_fu_1378_p2);

assign select_ln934_78_fu_1508_p3 = ((tmp_243_fu_1500_p3[0:0] == 1'b1) ? Range1_all_zeros_78_fu_1494_p2 : Range1_all_ones_78_fu_1488_p2);

assign select_ln934_79_fu_1618_p3 = ((tmp_246_fu_1610_p3[0:0] == 1'b1) ? Range1_all_zeros_79_fu_1604_p2 : Range1_all_ones_79_fu_1598_p2);

assign select_ln934_80_fu_1728_p3 = ((tmp_249_fu_1720_p3[0:0] == 1'b1) ? Range1_all_zeros_80_fu_1714_p2 : Range1_all_ones_80_fu_1708_p2);

assign select_ln934_81_fu_1838_p3 = ((tmp_252_fu_1830_p3[0:0] == 1'b1) ? Range1_all_zeros_81_fu_1824_p2 : Range1_all_ones_81_fu_1818_p2);

assign select_ln934_fu_298_p3 = ((tmp_fu_290_p3[0:0] == 1'b1) ? Range1_all_zeros_fu_284_p2 : Range1_all_ones_fu_278_p2);

assign tmp31_fu_268_p4 = {{p_read[15:10]}};

assign tmp_213_fu_400_p3 = p_Val2_141_fu_372_p2[32'd8];

assign tmp_216_fu_510_p3 = p_Val2_143_fu_482_p2[32'd8];

assign tmp_219_fu_620_p3 = p_Val2_145_fu_592_p2[32'd8];

assign tmp_222_fu_730_p3 = p_Val2_147_fu_702_p2[32'd8];

assign tmp_225_fu_840_p3 = p_Val2_149_fu_812_p2[32'd8];

assign tmp_228_fu_950_p3 = p_Val2_151_fu_922_p2[32'd8];

assign tmp_231_fu_1060_p3 = p_Val2_153_fu_1032_p2[32'd8];

assign tmp_234_fu_1170_p3 = p_Val2_155_fu_1142_p2[32'd8];

assign tmp_237_fu_1280_p3 = p_Val2_157_fu_1252_p2[32'd8];

assign tmp_240_fu_1390_p3 = p_Val2_159_fu_1362_p2[32'd8];

assign tmp_243_fu_1500_p3 = p_Val2_161_fu_1472_p2[32'd8];

assign tmp_246_fu_1610_p3 = p_Val2_163_fu_1582_p2[32'd8];

assign tmp_249_fu_1720_p3 = p_Val2_165_fu_1692_p2[32'd8];

assign tmp_252_fu_1830_p3 = p_Val2_167_fu_1802_p2[32'd8];

assign tmp_36_fu_378_p4 = {{p_read1[15:10]}};

assign tmp_73_fu_598_p4 = {{p_read3[15:10]}};

assign tmp_74_fu_708_p4 = {{p_read4[15:10]}};

assign tmp_75_fu_818_p4 = {{p_read5[15:10]}};

assign tmp_76_fu_928_p4 = {{p_read6[15:10]}};

assign tmp_77_fu_1038_p4 = {{p_read7[15:10]}};

assign tmp_78_fu_1148_p4 = {{p_read8[15:10]}};

assign tmp_79_fu_1258_p4 = {{p_read9[15:10]}};

assign tmp_80_fu_1368_p4 = {{p_read10[15:10]}};

assign tmp_81_fu_1478_p4 = {{p_read11[15:10]}};

assign tmp_82_fu_1588_p4 = {{p_read12[15:10]}};

assign tmp_83_fu_1698_p4 = {{p_read13[15:10]}};

assign tmp_84_fu_1808_p4 = {{p_read14[15:10]}};

assign tmp_fu_290_p3 = p_Val2_139_fu_262_p2[32'd8];

assign tmp_s_fu_488_p4 = {{p_read2[15:10]}};

assign zext_ln423_68_fu_368_p1 = and_ln420_68_fu_362_p2;

assign zext_ln423_69_fu_478_p1 = and_ln420_69_fu_472_p2;

assign zext_ln423_70_fu_588_p1 = and_ln420_70_fu_582_p2;

assign zext_ln423_71_fu_698_p1 = and_ln420_71_fu_692_p2;

assign zext_ln423_72_fu_808_p1 = and_ln420_72_fu_802_p2;

assign zext_ln423_73_fu_918_p1 = and_ln420_73_fu_912_p2;

assign zext_ln423_74_fu_1028_p1 = and_ln420_74_fu_1022_p2;

assign zext_ln423_75_fu_1138_p1 = and_ln420_75_fu_1132_p2;

assign zext_ln423_76_fu_1248_p1 = and_ln420_76_fu_1242_p2;

assign zext_ln423_77_fu_1358_p1 = and_ln420_77_fu_1352_p2;

assign zext_ln423_78_fu_1468_p1 = and_ln420_78_fu_1462_p2;

assign zext_ln423_79_fu_1578_p1 = and_ln420_79_fu_1572_p2;

assign zext_ln423_80_fu_1688_p1 = and_ln420_80_fu_1682_p2;

assign zext_ln423_81_fu_1798_p1 = and_ln420_81_fu_1792_p2;

assign zext_ln423_fu_258_p1 = and_ln420_fu_252_p2;

endmodule //tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config10_s
