// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config16_s (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;

wire   [0:0] p_Result_s_fu_140_p3;
wire   [0:0] p_Result_263_fu_120_p1;
wire   [0:0] and_ln420_fu_156_p2;
wire   [8:0] p_Val2_s_fu_130_p4;
wire   [8:0] zext_ln423_fu_162_p1;
wire   [5:0] tmp_9_fu_172_p4;
wire   [8:0] p_Val2_99_fu_166_p2;
wire   [0:0] tmp_fu_194_p3;
wire   [0:0] Range1_all_zeros_fu_188_p2;
wire   [0:0] Range1_all_ones_fu_182_p2;
wire   [0:0] p_Result_264_fu_148_p3;
wire   [0:0] select_ln934_fu_202_p3;
wire   [0:0] deleted_zeros_fu_210_p3;
wire   [0:0] icmp_ln1695_fu_124_p2;
wire   [8:0] select_ln348_fu_218_p3;
wire   [0:0] p_Result_247_fu_250_p3;
wire   [0:0] p_Result_265_fu_116_p1;
wire   [0:0] and_ln420_49_fu_266_p2;
wire   [8:0] p_Val2_100_fu_240_p4;
wire   [8:0] zext_ln423_49_fu_272_p1;
wire   [5:0] tmp_s_fu_282_p4;
wire   [8:0] p_Val2_101_fu_276_p2;
wire   [0:0] tmp_154_fu_304_p3;
wire   [0:0] Range1_all_zeros_49_fu_298_p2;
wire   [0:0] Range1_all_ones_49_fu_292_p2;
wire   [0:0] p_Result_266_fu_258_p3;
wire   [0:0] select_ln934_49_fu_312_p3;
wire   [0:0] deleted_zeros_49_fu_320_p3;
wire   [0:0] icmp_ln1695_49_fu_234_p2;
wire   [8:0] select_ln348_49_fu_328_p3;
wire   [0:0] p_Result_250_fu_360_p3;
wire   [0:0] p_Result_267_fu_112_p1;
wire   [0:0] and_ln420_50_fu_376_p2;
wire   [8:0] p_Val2_102_fu_350_p4;
wire   [8:0] zext_ln423_50_fu_382_p1;
wire   [5:0] tmp_57_fu_392_p4;
wire   [8:0] p_Val2_103_fu_386_p2;
wire   [0:0] tmp_157_fu_414_p3;
wire   [0:0] Range1_all_zeros_50_fu_408_p2;
wire   [0:0] Range1_all_ones_50_fu_402_p2;
wire   [0:0] p_Result_268_fu_368_p3;
wire   [0:0] select_ln934_50_fu_422_p3;
wire   [0:0] deleted_zeros_50_fu_430_p3;
wire   [0:0] icmp_ln1695_50_fu_344_p2;
wire   [8:0] select_ln348_50_fu_438_p3;
wire   [0:0] p_Result_253_fu_470_p3;
wire   [0:0] p_Result_269_fu_108_p1;
wire   [0:0] and_ln420_51_fu_486_p2;
wire   [8:0] p_Val2_104_fu_460_p4;
wire   [8:0] zext_ln423_51_fu_492_p1;
wire   [5:0] tmp_58_fu_502_p4;
wire   [8:0] p_Val2_105_fu_496_p2;
wire   [0:0] tmp_160_fu_524_p3;
wire   [0:0] Range1_all_zeros_51_fu_518_p2;
wire   [0:0] Range1_all_ones_51_fu_512_p2;
wire   [0:0] p_Result_270_fu_478_p3;
wire   [0:0] select_ln934_51_fu_532_p3;
wire   [0:0] deleted_zeros_51_fu_540_p3;
wire   [0:0] icmp_ln1695_51_fu_454_p2;
wire   [8:0] select_ln348_51_fu_548_p3;
wire   [0:0] p_Result_256_fu_580_p3;
wire   [0:0] p_Result_271_fu_104_p1;
wire   [0:0] and_ln420_52_fu_596_p2;
wire   [8:0] p_Val2_106_fu_570_p4;
wire   [8:0] zext_ln423_52_fu_602_p1;
wire   [5:0] tmp_59_fu_612_p4;
wire   [8:0] p_Val2_107_fu_606_p2;
wire   [0:0] tmp_163_fu_634_p3;
wire   [0:0] Range1_all_zeros_52_fu_628_p2;
wire   [0:0] Range1_all_ones_52_fu_622_p2;
wire   [0:0] p_Result_272_fu_588_p3;
wire   [0:0] select_ln934_52_fu_642_p3;
wire   [0:0] deleted_zeros_52_fu_650_p3;
wire   [0:0] icmp_ln1695_52_fu_564_p2;
wire   [8:0] select_ln348_52_fu_658_p3;
wire   [0:0] p_Result_259_fu_690_p3;
wire   [0:0] p_Result_273_fu_100_p1;
wire   [0:0] and_ln420_53_fu_706_p2;
wire   [8:0] p_Val2_108_fu_680_p4;
wire   [8:0] zext_ln423_53_fu_712_p1;
wire   [5:0] tmp_60_fu_722_p4;
wire   [8:0] p_Val2_109_fu_716_p2;
wire   [0:0] tmp_166_fu_744_p3;
wire   [0:0] Range1_all_zeros_53_fu_738_p2;
wire   [0:0] Range1_all_ones_53_fu_732_p2;
wire   [0:0] p_Result_274_fu_698_p3;
wire   [0:0] select_ln934_53_fu_752_p3;
wire   [0:0] deleted_zeros_53_fu_760_p3;
wire   [0:0] icmp_ln1695_53_fu_674_p2;
wire   [8:0] select_ln348_53_fu_768_p3;
wire   [0:0] p_Result_262_fu_800_p3;
wire   [0:0] p_Result_275_fu_96_p1;
wire   [0:0] and_ln420_54_fu_816_p2;
wire   [8:0] p_Val2_110_fu_790_p4;
wire   [8:0] zext_ln423_54_fu_822_p1;
wire   [5:0] tmp_61_fu_832_p4;
wire   [8:0] p_Val2_111_fu_826_p2;
wire   [0:0] tmp_169_fu_854_p3;
wire   [0:0] Range1_all_zeros_54_fu_848_p2;
wire   [0:0] Range1_all_ones_54_fu_842_p2;
wire   [0:0] p_Result_276_fu_808_p3;
wire   [0:0] select_ln934_54_fu_862_p3;
wire   [0:0] deleted_zeros_54_fu_870_p3;
wire   [0:0] icmp_ln1695_54_fu_784_p2;
wire   [8:0] select_ln348_54_fu_878_p3;
wire   [8:0] select_ln1695_fu_226_p3;
wire   [8:0] select_ln1695_49_fu_336_p3;
wire   [8:0] select_ln1695_50_fu_446_p3;
wire   [8:0] select_ln1695_51_fu_556_p3;
wire   [8:0] select_ln1695_52_fu_666_p3;
wire   [8:0] select_ln1695_53_fu_776_p3;
wire   [8:0] select_ln1695_54_fu_886_p3;
wire    ap_ce_reg;

assign Range1_all_ones_49_fu_292_p2 = ((tmp_s_fu_282_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_50_fu_402_p2 = ((tmp_57_fu_392_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_51_fu_512_p2 = ((tmp_58_fu_502_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_52_fu_622_p2 = ((tmp_59_fu_612_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_53_fu_732_p2 = ((tmp_60_fu_722_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_54_fu_842_p2 = ((tmp_61_fu_832_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_182_p2 = ((tmp_9_fu_172_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_49_fu_298_p2 = ((tmp_s_fu_282_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_50_fu_408_p2 = ((tmp_57_fu_392_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_51_fu_518_p2 = ((tmp_58_fu_502_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_52_fu_628_p2 = ((tmp_59_fu_612_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_53_fu_738_p2 = ((tmp_60_fu_722_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_54_fu_848_p2 = ((tmp_61_fu_832_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_188_p2 = ((tmp_9_fu_172_p4 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln420_49_fu_266_p2 = (p_Result_265_fu_116_p1 & p_Result_247_fu_250_p3);

assign and_ln420_50_fu_376_p2 = (p_Result_267_fu_112_p1 & p_Result_250_fu_360_p3);

assign and_ln420_51_fu_486_p2 = (p_Result_269_fu_108_p1 & p_Result_253_fu_470_p3);

assign and_ln420_52_fu_596_p2 = (p_Result_271_fu_104_p1 & p_Result_256_fu_580_p3);

assign and_ln420_53_fu_706_p2 = (p_Result_273_fu_100_p1 & p_Result_259_fu_690_p3);

assign and_ln420_54_fu_816_p2 = (p_Result_275_fu_96_p1 & p_Result_262_fu_800_p3);

assign and_ln420_fu_156_p2 = (p_Result_s_fu_140_p3 & p_Result_263_fu_120_p1);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1695_fu_226_p3;

assign ap_return_1 = select_ln1695_49_fu_336_p3;

assign ap_return_2 = select_ln1695_50_fu_446_p3;

assign ap_return_3 = select_ln1695_51_fu_556_p3;

assign ap_return_4 = select_ln1695_52_fu_666_p3;

assign ap_return_5 = select_ln1695_53_fu_776_p3;

assign ap_return_6 = select_ln1695_54_fu_886_p3;

assign deleted_zeros_49_fu_320_p3 = ((p_Result_266_fu_258_p3[0:0] == 1'b1) ? select_ln934_49_fu_312_p3 : Range1_all_zeros_49_fu_298_p2);

assign deleted_zeros_50_fu_430_p3 = ((p_Result_268_fu_368_p3[0:0] == 1'b1) ? select_ln934_50_fu_422_p3 : Range1_all_zeros_50_fu_408_p2);

assign deleted_zeros_51_fu_540_p3 = ((p_Result_270_fu_478_p3[0:0] == 1'b1) ? select_ln934_51_fu_532_p3 : Range1_all_zeros_51_fu_518_p2);

assign deleted_zeros_52_fu_650_p3 = ((p_Result_272_fu_588_p3[0:0] == 1'b1) ? select_ln934_52_fu_642_p3 : Range1_all_zeros_52_fu_628_p2);

assign deleted_zeros_53_fu_760_p3 = ((p_Result_274_fu_698_p3[0:0] == 1'b1) ? select_ln934_53_fu_752_p3 : Range1_all_zeros_53_fu_738_p2);

assign deleted_zeros_54_fu_870_p3 = ((p_Result_276_fu_808_p3[0:0] == 1'b1) ? select_ln934_54_fu_862_p3 : Range1_all_zeros_54_fu_848_p2);

assign deleted_zeros_fu_210_p3 = ((p_Result_264_fu_148_p3[0:0] == 1'b1) ? select_ln934_fu_202_p3 : Range1_all_zeros_fu_188_p2);

assign icmp_ln1695_49_fu_234_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_50_fu_344_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_51_fu_454_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_52_fu_564_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_53_fu_674_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_54_fu_784_p2 = (($signed(p_read8) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_fu_124_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign p_Result_247_fu_250_p3 = p_read2[32'd1];

assign p_Result_250_fu_360_p3 = p_read3[32'd1];

assign p_Result_253_fu_470_p3 = p_read5[32'd1];

assign p_Result_256_fu_580_p3 = p_read6[32'd1];

assign p_Result_259_fu_690_p3 = p_read7[32'd1];

assign p_Result_262_fu_800_p3 = p_read8[32'd1];

assign p_Result_263_fu_120_p1 = p_read1[0:0];

assign p_Result_264_fu_148_p3 = p_read1[32'd9];

assign p_Result_265_fu_116_p1 = p_read2[0:0];

assign p_Result_266_fu_258_p3 = p_read2[32'd9];

assign p_Result_267_fu_112_p1 = p_read3[0:0];

assign p_Result_268_fu_368_p3 = p_read3[32'd9];

assign p_Result_269_fu_108_p1 = p_read5[0:0];

assign p_Result_270_fu_478_p3 = p_read5[32'd9];

assign p_Result_271_fu_104_p1 = p_read6[0:0];

assign p_Result_272_fu_588_p3 = p_read6[32'd9];

assign p_Result_273_fu_100_p1 = p_read7[0:0];

assign p_Result_274_fu_698_p3 = p_read7[32'd9];

assign p_Result_275_fu_96_p1 = p_read8[0:0];

assign p_Result_276_fu_808_p3 = p_read8[32'd9];

assign p_Result_s_fu_140_p3 = p_read1[32'd1];

assign p_Val2_100_fu_240_p4 = {{p_read2[9:1]}};

assign p_Val2_101_fu_276_p2 = (p_Val2_100_fu_240_p4 + zext_ln423_49_fu_272_p1);

assign p_Val2_102_fu_350_p4 = {{p_read3[9:1]}};

assign p_Val2_103_fu_386_p2 = (p_Val2_102_fu_350_p4 + zext_ln423_50_fu_382_p1);

assign p_Val2_104_fu_460_p4 = {{p_read5[9:1]}};

assign p_Val2_105_fu_496_p2 = (p_Val2_104_fu_460_p4 + zext_ln423_51_fu_492_p1);

assign p_Val2_106_fu_570_p4 = {{p_read6[9:1]}};

assign p_Val2_107_fu_606_p2 = (p_Val2_106_fu_570_p4 + zext_ln423_52_fu_602_p1);

assign p_Val2_108_fu_680_p4 = {{p_read7[9:1]}};

assign p_Val2_109_fu_716_p2 = (p_Val2_108_fu_680_p4 + zext_ln423_53_fu_712_p1);

assign p_Val2_110_fu_790_p4 = {{p_read8[9:1]}};

assign p_Val2_111_fu_826_p2 = (p_Val2_110_fu_790_p4 + zext_ln423_54_fu_822_p1);

assign p_Val2_99_fu_166_p2 = (p_Val2_s_fu_130_p4 + zext_ln423_fu_162_p1);

assign p_Val2_s_fu_130_p4 = {{p_read1[9:1]}};

assign select_ln1695_49_fu_336_p3 = ((icmp_ln1695_49_fu_234_p2[0:0] == 1'b1) ? select_ln348_49_fu_328_p3 : 9'd0);

assign select_ln1695_50_fu_446_p3 = ((icmp_ln1695_50_fu_344_p2[0:0] == 1'b1) ? select_ln348_50_fu_438_p3 : 9'd0);

assign select_ln1695_51_fu_556_p3 = ((icmp_ln1695_51_fu_454_p2[0:0] == 1'b1) ? select_ln348_51_fu_548_p3 : 9'd0);

assign select_ln1695_52_fu_666_p3 = ((icmp_ln1695_52_fu_564_p2[0:0] == 1'b1) ? select_ln348_52_fu_658_p3 : 9'd0);

assign select_ln1695_53_fu_776_p3 = ((icmp_ln1695_53_fu_674_p2[0:0] == 1'b1) ? select_ln348_53_fu_768_p3 : 9'd0);

assign select_ln1695_54_fu_886_p3 = ((icmp_ln1695_54_fu_784_p2[0:0] == 1'b1) ? select_ln348_54_fu_878_p3 : 9'd0);

assign select_ln1695_fu_226_p3 = ((icmp_ln1695_fu_124_p2[0:0] == 1'b1) ? select_ln348_fu_218_p3 : 9'd0);

assign select_ln348_49_fu_328_p3 = ((deleted_zeros_49_fu_320_p3[0:0] == 1'b1) ? p_Val2_101_fu_276_p2 : 9'd511);

assign select_ln348_50_fu_438_p3 = ((deleted_zeros_50_fu_430_p3[0:0] == 1'b1) ? p_Val2_103_fu_386_p2 : 9'd511);

assign select_ln348_51_fu_548_p3 = ((deleted_zeros_51_fu_540_p3[0:0] == 1'b1) ? p_Val2_105_fu_496_p2 : 9'd511);

assign select_ln348_52_fu_658_p3 = ((deleted_zeros_52_fu_650_p3[0:0] == 1'b1) ? p_Val2_107_fu_606_p2 : 9'd511);

assign select_ln348_53_fu_768_p3 = ((deleted_zeros_53_fu_760_p3[0:0] == 1'b1) ? p_Val2_109_fu_716_p2 : 9'd511);

assign select_ln348_54_fu_878_p3 = ((deleted_zeros_54_fu_870_p3[0:0] == 1'b1) ? p_Val2_111_fu_826_p2 : 9'd511);

assign select_ln348_fu_218_p3 = ((deleted_zeros_fu_210_p3[0:0] == 1'b1) ? p_Val2_99_fu_166_p2 : 9'd511);

assign select_ln934_49_fu_312_p3 = ((tmp_154_fu_304_p3[0:0] == 1'b1) ? Range1_all_zeros_49_fu_298_p2 : Range1_all_ones_49_fu_292_p2);

assign select_ln934_50_fu_422_p3 = ((tmp_157_fu_414_p3[0:0] == 1'b1) ? Range1_all_zeros_50_fu_408_p2 : Range1_all_ones_50_fu_402_p2);

assign select_ln934_51_fu_532_p3 = ((tmp_160_fu_524_p3[0:0] == 1'b1) ? Range1_all_zeros_51_fu_518_p2 : Range1_all_ones_51_fu_512_p2);

assign select_ln934_52_fu_642_p3 = ((tmp_163_fu_634_p3[0:0] == 1'b1) ? Range1_all_zeros_52_fu_628_p2 : Range1_all_ones_52_fu_622_p2);

assign select_ln934_53_fu_752_p3 = ((tmp_166_fu_744_p3[0:0] == 1'b1) ? Range1_all_zeros_53_fu_738_p2 : Range1_all_ones_53_fu_732_p2);

assign select_ln934_54_fu_862_p3 = ((tmp_169_fu_854_p3[0:0] == 1'b1) ? Range1_all_zeros_54_fu_848_p2 : Range1_all_ones_54_fu_842_p2);

assign select_ln934_fu_202_p3 = ((tmp_fu_194_p3[0:0] == 1'b1) ? Range1_all_zeros_fu_188_p2 : Range1_all_ones_fu_182_p2);

assign tmp_154_fu_304_p3 = p_Val2_101_fu_276_p2[32'd8];

assign tmp_157_fu_414_p3 = p_Val2_103_fu_386_p2[32'd8];

assign tmp_160_fu_524_p3 = p_Val2_105_fu_496_p2[32'd8];

assign tmp_163_fu_634_p3 = p_Val2_107_fu_606_p2[32'd8];

assign tmp_166_fu_744_p3 = p_Val2_109_fu_716_p2[32'd8];

assign tmp_169_fu_854_p3 = p_Val2_111_fu_826_p2[32'd8];

assign tmp_57_fu_392_p4 = {{p_read3[15:10]}};

assign tmp_58_fu_502_p4 = {{p_read5[15:10]}};

assign tmp_59_fu_612_p4 = {{p_read6[15:10]}};

assign tmp_60_fu_722_p4 = {{p_read7[15:10]}};

assign tmp_61_fu_832_p4 = {{p_read8[15:10]}};

assign tmp_9_fu_172_p4 = {{p_read1[15:10]}};

assign tmp_fu_194_p3 = p_Val2_99_fu_166_p2[32'd8];

assign tmp_s_fu_282_p4 = {{p_read2[15:10]}};

assign zext_ln423_49_fu_272_p1 = and_ln420_49_fu_266_p2;

assign zext_ln423_50_fu_382_p1 = and_ln420_50_fu_376_p2;

assign zext_ln423_51_fu_492_p1 = and_ln420_51_fu_486_p2;

assign zext_ln423_52_fu_602_p1 = and_ln420_52_fu_596_p2;

assign zext_ln423_53_fu_712_p1 = and_ln420_53_fu_706_p2;

assign zext_ln423_54_fu_822_p1 = and_ln420_54_fu_816_p2;

assign zext_ln423_fu_162_p1 = and_ln420_fu_156_p2;

endmodule //tau_nn_relu_ap_fixed_16_6_5_3_0_ap_ufixed_9_0_4_0_0_relu_config16_s
